<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerOrders.Abstractions\CustomerOrders.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Vodovoz.Core.Domain">
      <HintPath>..\..\..\..\..\Desktop\Vodovoz\bin\Debug\Vodovoz.Core.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
