using System.ComponentModel.DataAnnotations;

namespace Sms.External.Interface
{
	public enum SmsResponseStatus
	{
		[Display(Name = "Сообщение не найдено")]
		Error = -1,
		[Display(Name = "Запрос выполнен или сообщение находится в нашей очереди")]
		MessageAccepted = 100,
		[Display(Name = "Сообщение передается оператору")]
		MessageTransmittedToTheOperator = 101,
		[Display(Name = "Сообщение отправлено (в пути)")]
		MessageOnThewWay = 102,
		[Display(Name = "Сообщение доставлено")]
		MessageDelivered = 103,
		[Display(Name = "Не может быть доставлено: время жизни истекло")]
		LifetimeHasExpired = 104,
		[Display(Name = "Не может быть доставлено: удалено оператором")]
		DeletedByOperator = 105,
		[Display(Name = "Не может быть доставлено: сбой в телефоне")]
		PhoneGlitch = 106,
		[Display(Name = "Не может быть доставлено: неизвестная причина")]
		UnknownReason = 107,
		[Display(Name = "Не может быть доставлено: отклонено")]
		Rejected = 108,
		[Display(Name = "Сообщение прочитано (для Viber, временно не работает)")]
		ViberMessageRead = 110,
		[Display(Name = "Не может быть доставлено: не найден маршрут на данный номер")]
		RouteNotFound = 150,
		[Display(Name = "Неправильный api_id")]
		WrongID = 200,
		[Display(Name = "Не хватает средств на лицевом счету")]
		OutOfMoney = 201,
		[Display(Name = "Неправильно указан номер телефона получателя, либо на него нет маршрута")]
		BadRecipient = 202,
		[Display(Name = "Нет текста сообщения")]
		MessageTextNotSpecified = 203,
		[Display(Name = "Имя отправителя не зарегистрировано у оператора получателя данного сообщения. Подайте заявку через раздел Отправители на сайте SMS.RU")]
		BadSender = 204,
		[Display(Name = "Сообщение слишком длинное (превышает 8 СМС)")]
		LongMessage = 205,
		[Display(Name = "Будет превышен или уже превышен дневной лимит на отправку сообщений")]
		DayMessageLimit = 206,
		[Display(Name = "На этот номер нет маршрута для доставки сообщений")]
		CantSendToThisNumber = 207,
		[Display(Name = "Параметр time указан неправильно")]
		WrongTime = 208,
		[Display(Name = "Вы добавили этот номер (или один из номеров) в стоп-лист")]
		BlacklistedRecepient = 209,
		[Display(Name = "Используется GET, где необходимо использовать POST")]
		ShouldUsePOST = 210,
		[Display(Name = "Метод не найден")]
		MethodNotFound = 211,
		[Display(Name = "Текст сообщения необходимо передать в кодировке UTF-8 (вы передали в другой кодировке")]
		WrongEncoding = 212,
		[Display(Name = "Указано более 5000 номеров в списке получателей")]
		LimitOfNumbers = 213,
		[Display(Name = "Номер находится зарубежом (включена настройка \"Отправлять только на номера РФ\")")]
		AbroadNumber = 214,
		[Display(Name = "Сервис временно недоступен, попробуйте чуть позже")]
		ServiceIsUnavailable = 220,
		[Display(Name = "Превышен общий лимит количества сообщений на этот номер в день")]
		DayMessagGeneralLimitToNumberPerDay = 230,
		[Display(Name = "Превышен лимит одинаковых сообщений на этот номер в минуту")]
		DayMessageLimitToNumberPerMinute = 231,
		[Display(Name = "Превышен лимит одинаковых сообщений на этот номер в день")]
		DayMessageLimitToNumber = 232,
		[Display(Name = "Превышен лимит отправки повторных сообщений с кодом на этот номер за короткий промежуток времени (\"защита от мошенников\", можно отключить в разделе \"Настройки\")")]
		DayMessagGeneralLimitToNumberPerShortTime = 233,
		[Display(Name = "Неправильный token (возможно истек срок действия, либо ваш IP изменился)")]
		WrongToken = 300,
		[Display(Name = "Неправильный api_id, либо логин/пароль")]
		WrongPassword = 301,
		[Display(Name = "Пользователь авторизован, но аккаунт не подтвержден (пользователь не ввел код, присланный в регистрационной смс)")]
		AccountNotVerified = 302,
		[Display(Name = "Код подтверждения неверен")]
		IncorrectVerificationCode = 303,
		[Display(Name = "Отправлено слишком много кодов подтверждения. Пожалуйста, повторите запрос позднее")]
		TooManyVerificationCodesSent = 304,
		[Display(Name = "Слишком много неверных вводов кода, повторите попытку позднее")]
		TooManyIncorrectCodesSent = 305,
		[Display(Name = "Ошибка на сервере. Повторите запрос.")]
		ServerErro = 500,
		[Display(Name = "Превышен лимит: IP пользователя из сети TOR, слишком много таких сообщений за короткий промежуток времени (можно настроить в ЛК).")]
		TorIp = 501,
		[Display(Name = "Превышен лимит: IP пользователя не совпадает с его страной, слишком много таких сообщений за короткий промежуток времени (можно настроить в ЛК).")]
		WrongCountryIp = 502,
		[Display(Name = "Превышен лимит: Слишком много сообщений в эту страну за короткий промежуток времени (можно настроить в ЛК).")]
		TooManyCountrySent = 503,
		[Display(Name = "Превышен лимит: Слишком много кодов авторизаций зарубеж за короткий промежуток времени (можно настроить в ЛК).")]
		TooManyAbroadSent = 504,
		[Display(Name = "Превышен лимит: Слишком много сообщений на один IP адрес (можно настроить в ЛК).")]
		TooManyOneIpSent = 505,
		[Display(Name = "Подсеть (ASN %s) IP адреса пользователя (%s) заблокирована, так как используется для атак.")]
		SubnetIsBlocked = 506,
		[Display(Name = "IP адрес пользователя указан неверно, либо идет из частный подсети (192.*, 10.*, итд).")]
		LocalIp = 507,
		[Display(Name = "Callback: URL неверный (не начинается на http://)")]
		WrongUrl = 901,
		[Display(Name = "Callback: Обработчик не найден (возможно был удален ранее)")]
		HandlerMissing = 902,
	}
}
