# stack name: mango_develop

version: "3.8"

services:

  service:
    image: docker.vod.qsolution.ru:5100/mango.service:develop
    ports:
      - 7984:7984
      - 7985:7985
    volumes:
      - /etc/vodovoz/mango.service/development/appsettings.Development.json:/app/appsettings.Development.json
      - /var/log/vodovoz/mango.service/development/:/var/log/mango.service
      - /etc/localtime:/etc/localtime:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:7985
    restart: unless-stopped
