
//Сформировать подпись для json в запросе можно тут: https://www.mango-office.ru/support/integratsiya-api/spisok_integratsiy/emulyator_api_virtualnoy_ats/
###
POST http://mango.vod.qsolution.ru:7985/mango/events/call
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="vpbx_api_key"
Content-Type: text/plain

j1dnx961y1rq9xcryxtuti5gtp3vp1h0
--Boundary
Content-Disposition: form-data; name="sign"
Content-Type: text/plain

6ca7a72a028894ec172d4dc386f11f2677fc394786e576511f253cdac250b9a3
--Boundary
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
"entry_id":"1MN0Q1MDOQ==",
"call_id":"MIxEyNTzTo6NDxkzNMMOzNQ==",
"timestamp":1558422128,
"seq":2,
"call_state":"Appeared",
"location":"abonent",
"from":
{
"number":"79876543210"
},
"to":
{
"extension":"55221",
"number":"sip:user00000@tech.mangosip.ru",
"line_number":"sip:line00000@tech.mangosip.ru",
"acd_group":"333"
},
"disconnect_reason":1131,
"dct":
{
"number":"74001234567",
"type":1
}
}
--Boundary--
