
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views
{
	public partial class UserView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.UserView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.UserView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
