
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Complaints
{
	public partial class GuiltyItemView
	{
		private global::Gtk.VBox vbxCreateGuilty;

		private global::Gamma.Widgets.ySpecComboBox yCmbResponsible;

		private global::QS.Widgets.GtkUI.EntityViewModelEntry entVmEmployee;

		private global::QS.Views.Control.EntityEntry entrySubdivision;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Complaints.GuiltyItemView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Complaints.GuiltyItemView";
			// Container child Vodovoz.Views.Complaints.GuiltyItemView.Gtk.Container+ContainerChild
			this.vbxCreateGuilty = new global::Gtk.VBox();
			this.vbxCreateGuilty.Name = "vbxCreateGuilty";
			this.vbxCreateGuilty.Spacing = 6;
			// Container child vbxCreateGuilty.Gtk.Box+BoxChild
			this.yCmbResponsible = new global::Gamma.Widgets.ySpecComboBox();
			this.yCmbResponsible.Name = "yCmbResponsible";
			this.yCmbResponsible.AddIfNotExist = false;
			this.yCmbResponsible.DefaultFirst = false;
			this.yCmbResponsible.ShowSpecialStateAll = true;
			this.yCmbResponsible.ShowSpecialStateNot = false;
			this.yCmbResponsible.NameForSpecialStateNot = "Нет";
			this.vbxCreateGuilty.Add(this.yCmbResponsible);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbxCreateGuilty[this.yCmbResponsible]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbxCreateGuilty.Gtk.Box+BoxChild
			this.entVmEmployee = new global::QS.Widgets.GtkUI.EntityViewModelEntry();
			this.entVmEmployee.Events = ((global::Gdk.EventMask)(256));
			this.entVmEmployee.Name = "entVmEmployee";
			this.entVmEmployee.CanEditReference = false;
			this.entVmEmployee.CanOpenWithoutTabParent = false;
			this.vbxCreateGuilty.Add(this.entVmEmployee);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbxCreateGuilty[this.entVmEmployee]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbxCreateGuilty.Gtk.Box+BoxChild
			this.entrySubdivision = new global::QS.Views.Control.EntityEntry();
			this.entrySubdivision.Events = ((global::Gdk.EventMask)(256));
			this.entrySubdivision.Name = "entrySubdivision";
			this.vbxCreateGuilty.Add(this.entrySubdivision);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbxCreateGuilty[this.entrySubdivision]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbxCreateGuilty);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
