
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views
{
	public partial class ManualCashlessIncomeMatchingView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnSave;

		private global::Gtk.Button btnCancel;

		private global::Gtk.VSeparator vseparator1;

		private global::Gamma.GtkWidgets.yHBox hboxPaymentsHandleBtns;

		private global::Gamma.GtkWidgets.yButton btnAddPayment;

		private global::Gtk.Button btnCompleteAllocation;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label lblIncomeNumberTitle;

		private global::Gtk.Label lblIncomeNumber;

		private global::Gtk.Label lblPayerTitle;

		private global::Gtk.Label lblPayer;

		private global::Gtk.Label lblDateTitle;

		private global::Gtk.Label lblDate;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblPurposeTitle;

		private global::Gtk.ScrolledWindow GtkScrolledWindowPurpose;

		private global::Gamma.GtkWidgets.yTextView textViewPurpose;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label lblIncomeSumTitle;

		private global::Gtk.Label lblIncomeSum;

		private global::Gtk.Label lblLastBalanceTitle;

		private global::Gamma.GtkWidgets.yLabel lblLastBalance;

		private global::Gtk.Label lblToAllocateTitle;

		private global::Gamma.GtkWidgets.yLabel lblToAllocate;

		private global::Gtk.HSeparator hseparator3;

		private global::Gamma.GtkWidgets.yVBox vboxPayments;

		private global::Gamma.GtkWidgets.yNotebook notebookPayments;

		private global::Gtk.Label lblPaymentTab;

		private global::Gtk.HSeparator hseparator2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.ManualCashlessIncomeMatchingView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.ManualCashlessIncomeMatchingView";
			// Container child Vodovoz.Views.ManualCashlessIncomeMatchingView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.btnSave.Image = w1;
			this.hbox1.Add(this.btnSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("Отмена");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.btnCancel.Image = w3;
			this.hbox1.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hboxPaymentsHandleBtns = new global::Gamma.GtkWidgets.yHBox();
			this.hboxPaymentsHandleBtns.Name = "hboxPaymentsHandleBtns";
			this.hboxPaymentsHandleBtns.Spacing = 6;
			// Container child hboxPaymentsHandleBtns.Gtk.Box+BoxChild
			this.btnAddPayment = new global::Gamma.GtkWidgets.yButton();
			this.btnAddPayment.CanFocus = true;
			this.btnAddPayment.Name = "btnAddPayment";
			this.btnAddPayment.UseUnderline = true;
			this.btnAddPayment.Label = global::Mono.Unix.Catalog.GetString("Добавить распределение");
			this.hboxPaymentsHandleBtns.Add(this.btnAddPayment);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxPaymentsHandleBtns[this.btnAddPayment]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxPaymentsHandleBtns.Gtk.Box+BoxChild
			this.btnCompleteAllocation = new global::Gtk.Button();
			this.btnCompleteAllocation.CanFocus = true;
			this.btnCompleteAllocation.Name = "btnCompleteAllocation";
			this.btnCompleteAllocation.UseUnderline = true;
			this.btnCompleteAllocation.Label = global::Mono.Unix.Catalog.GetString("Завершить распределение");
			this.hboxPaymentsHandleBtns.Add(this.btnCompleteAllocation);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxPaymentsHandleBtns[this.btnCompleteAllocation]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add(this.hboxPaymentsHandleBtns);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hboxPaymentsHandleBtns]));
			w8.Position = 3;
			this.vboxMain.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vboxMain.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hseparator1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblIncomeNumberTitle = new global::Gtk.Label();
			this.lblIncomeNumberTitle.Name = "lblIncomeNumberTitle";
			this.lblIncomeNumberTitle.LabelProp = global::Mono.Unix.Catalog.GetString("№ прихода:");
			this.hbox2.Add(this.lblIncomeNumberTitle);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblIncomeNumberTitle]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblIncomeNumber = new global::Gtk.Label();
			this.lblIncomeNumber.Name = "lblIncomeNumber";
			this.lblIncomeNumber.LabelProp = global::Mono.Unix.Catalog.GetString("incomeNum");
			this.hbox2.Add(this.lblIncomeNumber);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblIncomeNumber]));
			w12.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblPayerTitle = new global::Gtk.Label();
			this.lblPayerTitle.Name = "lblPayerTitle";
			this.lblPayerTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Плательщик:");
			this.hbox2.Add(this.lblPayerTitle);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblPayerTitle]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblPayer = new global::Gtk.Label();
			this.lblPayer.Name = "lblPayer";
			this.lblPayer.LabelProp = global::Mono.Unix.Catalog.GetString("Payer");
			this.hbox2.Add(this.lblPayer);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblPayer]));
			w14.Position = 3;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblDateTitle = new global::Gtk.Label();
			this.lblDateTitle.Name = "lblDateTitle";
			this.lblDateTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Дата:");
			this.hbox2.Add(this.lblDateTitle);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblDateTitle]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblDate = new global::Gtk.Label();
			this.lblDate.Name = "lblDate";
			this.lblDate.LabelProp = global::Mono.Unix.Catalog.GetString("Date");
			this.hbox2.Add(this.lblDate);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblDate]));
			w16.Position = 5;
			this.vboxMain.Add(this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblPurposeTitle = new global::Gtk.Label();
			this.lblPurposeTitle.Name = "lblPurposeTitle";
			this.lblPurposeTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Основание:");
			this.hbox3.Add(this.lblPurposeTitle);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblPurposeTitle]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindowPurpose = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowPurpose.HeightRequest = 45;
			this.GtkScrolledWindowPurpose.Name = "GtkScrolledWindowPurpose";
			this.GtkScrolledWindowPurpose.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowPurpose.Gtk.Container+ContainerChild
			this.textViewPurpose = new global::Gamma.GtkWidgets.yTextView();
			this.textViewPurpose.CanFocus = true;
			this.textViewPurpose.Name = "textViewPurpose";
			this.textViewPurpose.Editable = false;
			this.textViewPurpose.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindowPurpose.Add(this.textViewPurpose);
			this.hbox3.Add(this.GtkScrolledWindowPurpose);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindowPurpose]));
			w20.Position = 1;
			this.vboxMain.Add(this.hbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox3]));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblIncomeSumTitle = new global::Gtk.Label();
			this.lblIncomeSumTitle.Name = "lblIncomeSumTitle";
			this.lblIncomeSumTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Сумма прихода:");
			this.hbox4.Add(this.lblIncomeSumTitle);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblIncomeSumTitle]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblIncomeSum = new global::Gtk.Label();
			this.lblIncomeSum.Name = "lblIncomeSum";
			this.lblIncomeSum.LabelProp = global::Mono.Unix.Catalog.GetString("TotalSum");
			this.hbox4.Add(this.lblIncomeSum);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblIncomeSum]));
			w23.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblLastBalanceTitle = new global::Gtk.Label();
			this.lblLastBalanceTitle.Name = "lblLastBalanceTitle";
			this.lblLastBalanceTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Прошлый остаток:");
			this.hbox4.Add(this.lblLastBalanceTitle);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblLastBalanceTitle]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblLastBalance = new global::Gamma.GtkWidgets.yLabel();
			this.lblLastBalance.Name = "lblLastBalance";
			this.lblLastBalance.LabelProp = global::Mono.Unix.Catalog.GetString("LastBalance");
			this.hbox4.Add(this.lblLastBalance);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblLastBalance]));
			w25.Position = 3;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblToAllocateTitle = new global::Gtk.Label();
			this.lblToAllocateTitle.Name = "lblToAllocateTitle";
			this.lblToAllocateTitle.LabelProp = global::Mono.Unix.Catalog.GetString("К распределению:");
			this.hbox4.Add(this.lblToAllocateTitle);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblToAllocateTitle]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblToAllocate = new global::Gamma.GtkWidgets.yLabel();
			this.lblToAllocate.Name = "lblToAllocate";
			this.lblToAllocate.LabelProp = global::Mono.Unix.Catalog.GetString("ToAllocate");
			this.hbox4.Add(this.lblToAllocate);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblToAllocate]));
			w27.Position = 5;
			this.vboxMain.Add(this.hbox4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox4]));
			w28.Position = 4;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vboxMain.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hseparator3]));
			w29.Position = 5;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxPayments = new global::Gamma.GtkWidgets.yVBox();
			this.vboxPayments.Name = "vboxPayments";
			this.vboxPayments.Spacing = 6;
			// Container child vboxPayments.Gtk.Box+BoxChild
			this.notebookPayments = new global::Gamma.GtkWidgets.yNotebook();
			this.notebookPayments.CanFocus = true;
			this.notebookPayments.Name = "notebookPayments";
			this.notebookPayments.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w30 = new global::Gtk.Label();
			w30.Visible = true;
			this.notebookPayments.Add(w30);
			this.lblPaymentTab = new global::Gtk.Label();
			this.lblPaymentTab.Name = "lblPaymentTab";
			this.lblPaymentTab.LabelProp = global::Mono.Unix.Catalog.GetString("Платеж");
			this.notebookPayments.SetTabLabel(w30, this.lblPaymentTab);
			this.lblPaymentTab.ShowAll();
			this.vboxPayments.Add(this.notebookPayments);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxPayments[this.notebookPayments]));
			w31.Position = 0;
			this.vboxMain.Add(this.vboxPayments);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.vboxPayments]));
			w32.Position = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vboxMain.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hseparator2]));
			w33.Position = 7;
			w33.Expand = false;
			w33.Fill = false;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
