
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Logistic
{
	public partial class LogisticsRequirementsView
	{
		private global::Gamma.GtkWidgets.yVBox yvboxMain;

		private global::Gtk.ScrolledWindow scrolledwindowMain;

		private global::Gamma.GtkWidgets.yTable ytableRequirements;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonDocuments;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonForwarder;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonLargus;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonNationality;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonPass;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Logistic.LogisticsRequirementsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Logistic.LogisticsRequirementsView";
			// Container child Vodovoz.Views.Logistic.LogisticsRequirementsView.Gtk.Container+ContainerChild
			this.yvboxMain = new global::Gamma.GtkWidgets.yVBox();
			this.yvboxMain.Name = "yvboxMain";
			this.yvboxMain.Spacing = 6;
			// Container child yvboxMain.Gtk.Box+BoxChild
			this.scrolledwindowMain = new global::Gtk.ScrolledWindow();
			this.scrolledwindowMain.CanFocus = true;
			this.scrolledwindowMain.Name = "scrolledwindowMain";
			this.scrolledwindowMain.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowMain.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.ytableRequirements = new global::Gamma.GtkWidgets.yTable();
			this.ytableRequirements.Name = "ytableRequirements";
			this.ytableRequirements.NRows = ((uint)(5));
			this.ytableRequirements.RowSpacing = ((uint)(6));
			this.ytableRequirements.ColumnSpacing = ((uint)(6));
			// Container child ytableRequirements.Gtk.Table+TableChild
			this.ycheckbuttonDocuments = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonDocuments.CanFocus = true;
			this.ycheckbuttonDocuments.Name = "ycheckbuttonDocuments";
			this.ycheckbuttonDocuments.Label = global::Mono.Unix.Catalog.GetString("Наличие паспорта/документов у водителя: \"Д\" на карте");
			this.ycheckbuttonDocuments.DrawIndicator = true;
			this.ycheckbuttonDocuments.UseUnderline = true;
			this.ytableRequirements.Add(this.ycheckbuttonDocuments);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ytableRequirements[this.ycheckbuttonDocuments]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytableRequirements.Gtk.Table+TableChild
			this.ycheckbuttonForwarder = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonForwarder.CanFocus = true;
			this.ycheckbuttonForwarder.Name = "ycheckbuttonForwarder";
			this.ycheckbuttonForwarder.Label = global::Mono.Unix.Catalog.GetString("Требуется экспедитор на адресе: \"Э\" на карте");
			this.ycheckbuttonForwarder.DrawIndicator = true;
			this.ycheckbuttonForwarder.UseUnderline = true;
			this.ytableRequirements.Add(this.ycheckbuttonForwarder);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.ytableRequirements[this.ycheckbuttonForwarder]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytableRequirements.Gtk.Table+TableChild
			this.ycheckbuttonLargus = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonLargus.CanFocus = true;
			this.ycheckbuttonLargus.Name = "ycheckbuttonLargus";
			this.ycheckbuttonLargus.Label = global::Mono.Unix.Catalog.GetString("Только ларгус (газель не проедет): \"Л\" на карте");
			this.ycheckbuttonLargus.DrawIndicator = true;
			this.ycheckbuttonLargus.UseUnderline = true;
			this.ytableRequirements.Add(this.ycheckbuttonLargus);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.ytableRequirements[this.ycheckbuttonLargus]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytableRequirements.Gtk.Table+TableChild
			this.ycheckbuttonNationality = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonNationality.CanFocus = true;
			this.ycheckbuttonNationality.Name = "ycheckbuttonNationality";
			this.ycheckbuttonNationality.Label = global::Mono.Unix.Catalog.GetString("Требуется русский водитель: \"Р\" на карте");
			this.ycheckbuttonNationality.DrawIndicator = true;
			this.ycheckbuttonNationality.UseUnderline = true;
			this.ytableRequirements.Add(this.ycheckbuttonNationality);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.ytableRequirements[this.ycheckbuttonNationality]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytableRequirements.Gtk.Table+TableChild
			this.ycheckbuttonPass = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonPass.CanFocus = true;
			this.ycheckbuttonPass.Name = "ycheckbuttonPass";
			this.ycheckbuttonPass.Label = global::Mono.Unix.Catalog.GetString("Требуется пропуск: \"П\" на карте");
			this.ycheckbuttonPass.DrawIndicator = true;
			this.ycheckbuttonPass.UseUnderline = true;
			this.ytableRequirements.Add(this.ycheckbuttonPass);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.ytableRequirements[this.ycheckbuttonPass]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.ytableRequirements);
			this.scrolledwindowMain.Add(w1);
			this.yvboxMain.Add(this.scrolledwindowMain);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.yvboxMain[this.scrolledwindowMain]));
			w9.Position = 0;
			this.Add(this.yvboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
