
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Filters.GtkViews
{
	public partial class CarFilterView
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Table table1;

		private global::QS.Views.Control.EntityEntry entityentryCarOwner;

		private global::QS.Views.Control.EntityEntry entityentryInsurer;

		private global::QS.Views.Control.EntityEntry entryModel;

		private global::Gtk.ScrolledWindow GtkScrolledWindowOwnType;

		private global::Gamma.Widgets.EnumCheckList enumcheckCarOwnType;

		private global::Gtk.ScrolledWindow GtkScrolledWindowTypeOfUse;

		private global::Gamma.Widgets.EnumCheckList enumcheckCarTypeOfUse;

		private global::Gtk.HBox hbox2;

		private global::QS.Widgets.NullableCheckButton nullablecheckArchive;

		private global::Gtk.HBox hbox3;

		private global::QS.Widgets.NullableCheckButton nullablecheckVisitingMaster;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonCarsWithoutInsurance;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonCarsWithoutOwner;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonNotUsedInDelivery;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonUsedInDelivery;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.yLabel ylabelArchive;

		private global::Gamma.GtkWidgets.yLabel ylabelCarOwner;

		private global::Gamma.GtkWidgets.yLabel ylabelInsurer;

		private global::Gamma.GtkWidgets.yLabel ylabelModel;

		private global::Gamma.GtkWidgets.yLabel ylabelOwnType;

		private global::Gamma.GtkWidgets.yLabel ylabelTypeOfUse;

		private global::Gamma.GtkWidgets.yLabel ylabelUsedInDelivery;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Filters.GtkViews.CarFilterView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Filters.GtkViews.CarFilterView";
			// Container child Vodovoz.Filters.GtkViews.CarFilterView.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(8)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.entityentryCarOwner = new global::QS.Views.Control.EntityEntry();
			this.entityentryCarOwner.Events = ((global::Gdk.EventMask)(256));
			this.entityentryCarOwner.Name = "entityentryCarOwner";
			this.table1.Add(this.entityentryCarOwner);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.entityentryCarOwner]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(5));
			w2.RightAttach = ((uint)(6));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.entityentryInsurer = new global::QS.Views.Control.EntityEntry();
			this.entityentryInsurer.Events = ((global::Gdk.EventMask)(256));
			this.entityentryInsurer.Name = "entityentryInsurer";
			this.table1.Add(this.entityentryInsurer);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.entityentryInsurer]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(5));
			w3.RightAttach = ((uint)(6));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.entryModel = new global::QS.Views.Control.EntityEntry();
			this.entryModel.Events = ((global::Gdk.EventMask)(256));
			this.entryModel.Name = "entryModel";
			this.table1.Add(this.entryModel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.entryModel]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindowOwnType = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowOwnType.WidthRequest = 200;
			this.GtkScrolledWindowOwnType.Name = "GtkScrolledWindowOwnType";
			this.GtkScrolledWindowOwnType.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowOwnType.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.enumcheckCarOwnType = new global::Gamma.Widgets.EnumCheckList();
			this.enumcheckCarOwnType.Name = "enumcheckCarOwnType";
			w5.Add(this.enumcheckCarOwnType);
			this.GtkScrolledWindowOwnType.Add(w5);
			this.table1.Add(this.GtkScrolledWindowOwnType);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindowOwnType]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindowTypeOfUse = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowTypeOfUse.WidthRequest = 200;
			this.GtkScrolledWindowTypeOfUse.Name = "GtkScrolledWindowTypeOfUse";
			this.GtkScrolledWindowTypeOfUse.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowTypeOfUse.Gtk.Container+ContainerChild
			global::Gtk.Viewport w9 = new global::Gtk.Viewport();
			w9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.enumcheckCarTypeOfUse = new global::Gamma.Widgets.EnumCheckList();
			this.enumcheckCarTypeOfUse.Name = "enumcheckCarTypeOfUse";
			w9.Add(this.enumcheckCarTypeOfUse);
			this.GtkScrolledWindowTypeOfUse.Add(w9);
			this.table1.Add(this.GtkScrolledWindowTypeOfUse);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindowTypeOfUse]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.nullablecheckArchive = new global::QS.Widgets.NullableCheckButton();
			this.nullablecheckArchive.CanFocus = true;
			this.nullablecheckArchive.Name = "nullablecheckArchive";
			this.nullablecheckArchive.UseUnderline = true;
			this.hbox2.Add(this.nullablecheckArchive);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.nullablecheckArchive]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.table1.Add(this.hbox2);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox2]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.nullablecheckVisitingMaster = new global::QS.Widgets.NullableCheckButton();
			this.nullablecheckVisitingMaster.CanFocus = true;
			this.nullablecheckVisitingMaster.Name = "nullablecheckVisitingMaster";
			this.nullablecheckVisitingMaster.UseUnderline = true;
			this.hbox3.Add(this.nullablecheckVisitingMaster);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.nullablecheckVisitingMaster]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.table1.Add(this.hbox3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox3]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonCarsWithoutInsurance = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonCarsWithoutInsurance.CanFocus = true;
			this.ycheckbuttonCarsWithoutInsurance.Name = "ycheckbuttonCarsWithoutInsurance";
			this.ycheckbuttonCarsWithoutInsurance.Label = global::Mono.Unix.Catalog.GetString("Авто без страховщика");
			this.ycheckbuttonCarsWithoutInsurance.DrawIndicator = true;
			this.ycheckbuttonCarsWithoutInsurance.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonCarsWithoutInsurance);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonCarsWithoutInsurance]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(6));
			w17.RightAttach = ((uint)(7));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonCarsWithoutOwner = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonCarsWithoutOwner.CanFocus = true;
			this.ycheckbuttonCarsWithoutOwner.Name = "ycheckbuttonCarsWithoutOwner";
			this.ycheckbuttonCarsWithoutOwner.Label = global::Mono.Unix.Catalog.GetString("Авто без собственника");
			this.ycheckbuttonCarsWithoutOwner.DrawIndicator = true;
			this.ycheckbuttonCarsWithoutOwner.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonCarsWithoutOwner);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonCarsWithoutOwner]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(6));
			w18.RightAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonNotUsedInDelivery = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonNotUsedInDelivery.CanFocus = true;
			this.ycheckbuttonNotUsedInDelivery.Name = "ycheckbuttonNotUsedInDelivery";
			this.ycheckbuttonNotUsedInDelivery.Label = global::Mono.Unix.Catalog.GetString("Не участвует");
			this.ycheckbuttonNotUsedInDelivery.DrawIndicator = true;
			this.ycheckbuttonNotUsedInDelivery.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonNotUsedInDelivery);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonNotUsedInDelivery]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(7));
			w19.RightAttach = ((uint)(8));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonUsedInDelivery = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonUsedInDelivery.CanFocus = true;
			this.ycheckbuttonUsedInDelivery.Name = "ycheckbuttonUsedInDelivery";
			this.ycheckbuttonUsedInDelivery.Label = global::Mono.Unix.Catalog.GetString("Участвует");
			this.ycheckbuttonUsedInDelivery.DrawIndicator = true;
			this.ycheckbuttonUsedInDelivery.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonUsedInDelivery);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonUsedInDelivery]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(7));
			w20.RightAttach = ((uint)(8));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 1F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Водитель - выездной мастер:");
			this.table1.Add(this.ylabel1);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabel1]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelArchive = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelArchive.Name = "ylabelArchive";
			this.ylabelArchive.Xalign = 1F;
			this.ylabelArchive.LabelProp = global::Mono.Unix.Catalog.GetString("Архивные:");
			this.table1.Add(this.ylabelArchive);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelArchive]));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelCarOwner = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelCarOwner.Name = "ylabelCarOwner";
			this.ylabelCarOwner.Xalign = 1F;
			this.ylabelCarOwner.LabelProp = global::Mono.Unix.Catalog.GetString("Собственник:");
			this.table1.Add(this.ylabelCarOwner);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelCarOwner]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(4));
			w23.RightAttach = ((uint)(5));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelInsurer = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelInsurer.Name = "ylabelInsurer";
			this.ylabelInsurer.Xalign = 1F;
			this.ylabelInsurer.LabelProp = global::Mono.Unix.Catalog.GetString("Страховщик:");
			this.table1.Add(this.ylabelInsurer);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelInsurer]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(4));
			w24.RightAttach = ((uint)(5));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelModel = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelModel.Name = "ylabelModel";
			this.ylabelModel.Xalign = 1F;
			this.ylabelModel.LabelProp = global::Mono.Unix.Catalog.GetString("Модель:");
			this.table1.Add(this.ylabelModel);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelModel]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelOwnType = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOwnType.Name = "ylabelOwnType";
			this.ylabelOwnType.LabelProp = global::Mono.Unix.Catalog.GetString("Принадлежность:");
			this.table1.Add(this.ylabelOwnType);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelOwnType]));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelTypeOfUse = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelTypeOfUse.Name = "ylabelTypeOfUse";
			this.ylabelTypeOfUse.LabelProp = global::Mono.Unix.Catalog.GetString("Тип:");
			this.table1.Add(this.ylabelTypeOfUse);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelTypeOfUse]));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelUsedInDelivery = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelUsedInDelivery.Name = "ylabelUsedInDelivery";
			this.ylabelUsedInDelivery.LabelProp = global::Mono.Unix.Catalog.GetString("Участие в доставке:");
			this.table1.Add(this.ylabelUsedInDelivery);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelUsedInDelivery]));
			w28.LeftAttach = ((uint)(7));
			w28.RightAttach = ((uint)(8));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table1);
			this.GtkScrolledWindow.Add(w1);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
