
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Client.CounterpartyClassification
{
	public partial class CounterpartyClassificationCalculationView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Client.CounterpartyClassification.CounterpartyClassificationCalculationView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Client.CounterpartyClassification.CounterpartyClassificationCalcula" +
				"tionView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
