
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders.OrdersWithoutShipment
{
	public partial class OrderWithoutShipmentForDebtView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox5;

		private global::Gamma.GtkWidgets.yButton btnCancel;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.yLabel ylabelOrderNum;

		private global::Gamma.GtkWidgets.yLabel ylabel3;

		private global::Gamma.GtkWidgets.yLabel ylabelOrderDate;

		private global::Gamma.GtkWidgets.yLabel ylabel5;

		private global::Gamma.GtkWidgets.yLabel ylabelOrderAuthor;

		private global::Gtk.HBox hbox2;

		private global::Gamma.GtkWidgets.yLabel ylabel7;

		private global::QS.Widgets.GtkUI.EntityViewModelEntry entityViewModelEntryCounterparty;

		private global::Gamma.GtkWidgets.yLabel lblOrganization;

		private global::QS.Views.Control.EntityEntry organizationEntry;

		private global::Gtk.HBox hbox4;

		private global::Gamma.GtkWidgets.yEntry yentryDebtName;

		private global::Gamma.GtkWidgets.ySpinButton yspinbtnDebtSum;

		private global::Gamma.GtkWidgets.yButton ybtnOpenBill;

		private global::Gamma.GtkWidgets.yCheckButton yCheckBtnHideSignature;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vboxEdo;

		private global::Gamma.GtkWidgets.yLabel ylabel4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow10;

		private global::Gamma.GtkWidgets.yTreeView treeViewEdoContainers;

		private global::Gamma.GtkWidgets.yHBox hboxEdoContainersBtns;

		private global::Gamma.GtkWidgets.yButton btnUpdateEdoDocFlowStatus;

		private global::Gamma.GtkWidgets.yButton ybuttonSendDocumentAgain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.OrdersWithoutShipment.OrderWithoutShipmentForDebtView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.OrdersWithoutShipment.OrderWithoutShipmentForDebtView";
			// Container child Vodovoz.Views.Orders.OrdersWithoutShipment.OrderWithoutShipmentForDebtView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnCancel = new global::Gamma.GtkWidgets.yButton();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("Отмена");
			this.hbox5.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnCancel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Счет без отгрузки на долг № Ф");
			this.hbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabelOrderNum = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOrderNum.Name = "ylabelOrderNum";
			this.ylabelOrderNum.Xalign = 0F;
			this.ylabelOrderNum.LabelProp = global::Mono.Unix.Catalog.GetString("orderNum");
			this.hbox1.Add(this.ylabelOrderNum);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabelOrderNum]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel3 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel3.Name = "ylabel3";
			this.ylabel3.LabelProp = global::Mono.Unix.Catalog.GetString(" от ");
			this.hbox1.Add(this.ylabel3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel3]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabelOrderDate = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOrderDate.Name = "ylabelOrderDate";
			this.ylabelOrderDate.LabelProp = global::Mono.Unix.Catalog.GetString("orderDate");
			this.hbox1.Add(this.ylabelOrderDate);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabelOrderDate]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel5 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel5.Name = "ylabel5";
			this.ylabel5.LabelProp = global::Mono.Unix.Catalog.GetString(" Автор: ");
			this.hbox1.Add(this.ylabel5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel5]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabelOrderAuthor = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOrderAuthor.Name = "ylabelOrderAuthor";
			this.ylabelOrderAuthor.LabelProp = global::Mono.Unix.Catalog.GetString("author");
			this.hbox1.Add(this.ylabelOrderAuthor);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabelOrderAuthor]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 7;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ylabel7 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel7.Name = "ylabel7";
			this.ylabel7.LabelProp = global::Mono.Unix.Catalog.GetString("Контрагент: ");
			this.hbox2.Add(this.ylabel7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ylabel7]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entityViewModelEntryCounterparty = new global::QS.Widgets.GtkUI.EntityViewModelEntry();
			this.entityViewModelEntryCounterparty.Events = ((global::Gdk.EventMask)(256));
			this.entityViewModelEntryCounterparty.Name = "entityViewModelEntryCounterparty";
			this.entityViewModelEntryCounterparty.CanEditReference = false;
			this.entityViewModelEntryCounterparty.CanDisposeEntitySelectorFactory = false;
			this.entityViewModelEntryCounterparty.CanOpenWithoutTabParent = false;
			this.hbox2.Add(this.entityViewModelEntryCounterparty);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entityViewModelEntryCounterparty]));
			w11.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblOrganization = new global::Gamma.GtkWidgets.yLabel();
			this.lblOrganization.Name = "lblOrganization";
			this.lblOrganization.Xalign = 1F;
			this.lblOrganization.LabelProp = global::Mono.Unix.Catalog.GetString("Организация:");
			this.hbox2.Add(this.lblOrganization);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblOrganization]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.organizationEntry = new global::QS.Views.Control.EntityEntry();
			this.organizationEntry.Events = ((global::Gdk.EventMask)(256));
			this.organizationEntry.Name = "organizationEntry";
			this.hbox2.Add(this.organizationEntry);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.organizationEntry]));
			w13.Position = 3;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yentryDebtName = new global::Gamma.GtkWidgets.yEntry();
			this.yentryDebtName.WidthRequest = 350;
			this.yentryDebtName.CanFocus = true;
			this.yentryDebtName.Name = "yentryDebtName";
			this.yentryDebtName.IsEditable = true;
			this.yentryDebtName.InvisibleChar = '•';
			this.hbox4.Add(this.yentryDebtName);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yentryDebtName]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yspinbtnDebtSum = new global::Gamma.GtkWidgets.ySpinButton(0D, 100000000D, 1D);
			this.yspinbtnDebtSum.CanFocus = true;
			this.yspinbtnDebtSum.Name = "yspinbtnDebtSum";
			this.yspinbtnDebtSum.Adjustment.PageIncrement = 10D;
			this.yspinbtnDebtSum.ClimbRate = 1D;
			this.yspinbtnDebtSum.Digits = ((uint)(2));
			this.yspinbtnDebtSum.Numeric = true;
			this.yspinbtnDebtSum.ValueAsDecimal = 0m;
			this.yspinbtnDebtSum.ValueAsInt = 0;
			this.hbox4.Add(this.yspinbtnDebtSum);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yspinbtnDebtSum]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ybtnOpenBill = new global::Gamma.GtkWidgets.yButton();
			this.ybtnOpenBill.CanFocus = true;
			this.ybtnOpenBill.Name = "ybtnOpenBill";
			this.ybtnOpenBill.UseUnderline = true;
			this.ybtnOpenBill.Label = global::Mono.Unix.Catalog.GetString("Открыть счет");
			this.hbox4.Add(this.ybtnOpenBill);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.ybtnOpenBill]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yCheckBtnHideSignature = new global::Gamma.GtkWidgets.yCheckButton();
			this.yCheckBtnHideSignature.CanFocus = true;
			this.yCheckBtnHideSignature.Name = "yCheckBtnHideSignature";
			this.yCheckBtnHideSignature.Label = global::Mono.Unix.Catalog.GetString("Счет без печати и подписей");
			this.yCheckBtnHideSignature.DrawIndicator = true;
			this.yCheckBtnHideSignature.UseUnderline = true;
			this.hbox4.Add(this.yCheckBtnHideSignature);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yCheckBtnHideSignature]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			this.vbox1.Add(this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
			w20.Position = 4;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vboxEdo = new global::Gtk.VBox();
			this.vboxEdo.Name = "vboxEdo";
			this.vboxEdo.Spacing = 6;
			// Container child vboxEdo.Gtk.Box+BoxChild
			this.ylabel4 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel4.Name = "ylabel4";
			this.ylabel4.Xalign = 0F;
			this.ylabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Электронные документы:");
			this.vboxEdo.Add(this.ylabel4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxEdo[this.ylabel4]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vboxEdo.Gtk.Box+BoxChild
			this.GtkScrolledWindow10 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow10.Name = "GtkScrolledWindow10";
			this.GtkScrolledWindow10.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow10.Gtk.Container+ContainerChild
			this.treeViewEdoContainers = new global::Gamma.GtkWidgets.yTreeView();
			this.treeViewEdoContainers.CanFocus = true;
			this.treeViewEdoContainers.Name = "treeViewEdoContainers";
			this.GtkScrolledWindow10.Add(this.treeViewEdoContainers);
			this.vboxEdo.Add(this.GtkScrolledWindow10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxEdo[this.GtkScrolledWindow10]));
			w23.Position = 1;
			// Container child vboxEdo.Gtk.Box+BoxChild
			this.hboxEdoContainersBtns = new global::Gamma.GtkWidgets.yHBox();
			this.hboxEdoContainersBtns.Name = "hboxEdoContainersBtns";
			this.hboxEdoContainersBtns.Spacing = 6;
			// Container child hboxEdoContainersBtns.Gtk.Box+BoxChild
			this.btnUpdateEdoDocFlowStatus = new global::Gamma.GtkWidgets.yButton();
			this.btnUpdateEdoDocFlowStatus.CanFocus = true;
			this.btnUpdateEdoDocFlowStatus.Name = "btnUpdateEdoDocFlowStatus";
			this.btnUpdateEdoDocFlowStatus.UseUnderline = true;
			this.btnUpdateEdoDocFlowStatus.Label = global::Mono.Unix.Catalog.GetString("Обновить статус");
			this.hboxEdoContainersBtns.Add(this.btnUpdateEdoDocFlowStatus);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hboxEdoContainersBtns[this.btnUpdateEdoDocFlowStatus]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hboxEdoContainersBtns.Gtk.Box+BoxChild
			this.ybuttonSendDocumentAgain = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonSendDocumentAgain.CanFocus = true;
			this.ybuttonSendDocumentAgain.Name = "ybuttonSendDocumentAgain";
			this.ybuttonSendDocumentAgain.UseUnderline = true;
			this.ybuttonSendDocumentAgain.Label = global::Mono.Unix.Catalog.GetString("Отправить повторно");
			this.hboxEdoContainersBtns.Add(this.ybuttonSendDocumentAgain);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hboxEdoContainersBtns[this.ybuttonSendDocumentAgain]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vboxEdo.Add(this.hboxEdoContainersBtns);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxEdo[this.hboxEdoContainersBtns]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox1.Add(this.vboxEdo);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vboxEdo]));
			w27.Position = 5;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
