<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Business\Vodovoz.Core.Data.NHibernate\Vodovoz.Core.Data.NHibernate.csproj" />
    <ProjectReference Include="..\..\..\Business\Vodovoz.Core.Data\Vodovoz.Core.Data.csproj" />
    <ProjectReference Include="..\..\..\Notifications\EdoNotifications\EdoNotifications.Application\EdoNotifications.Application.csproj" />
    <ProjectReference Include="..\..\..\Notifications\EdoNotifications\EdoNotifications.Contracts\EdoNotifications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Notifications\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\BackendInfrastructure\BackendInfrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageTransport\MessageTransport.csproj" />
    <ProjectReference Include="..\Edo.Common\Edo.Common.csproj" />
    <ProjectReference Include="..\Edo.Problems\Edo.Problems.csproj" />
    <ProjectReference Include="..\Edo.Contracts\Edo.Contracts.csproj" />
    <ProjectReference Include="..\Edo.Transport\Edo.Transport.csproj" />
  </ItemGroup>

</Project>
