
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.JournalFilters
{
	public partial class NomenclatureRepFilter
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Label labelType;

		private global::Gamma.Widgets.yEnumComboBox enumcomboCategory;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.JournalFilters.NomenclatureRepFilter
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.JournalFilters.NomenclatureRepFilter";
			// Container child Vodovoz.JournalFilters.NomenclatureRepFilter.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelType = new global::Gtk.Label();
			this.labelType.Name = "labelType";
			this.labelType.LabelProp = global::Mono.Unix.Catalog.GetString("Категория");
			this.hbox1.Add(this.labelType);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelType]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.enumcomboCategory = new global::Gamma.Widgets.yEnumComboBox();
			this.enumcomboCategory.Name = "enumcomboCategory";
			this.enumcomboCategory.ShowSpecialStateAll = true;
			this.enumcomboCategory.ShowSpecialStateNot = false;
			this.enumcomboCategory.UseShortTitle = false;
			this.enumcomboCategory.DefaultFirst = true;
			this.hbox1.Add(this.enumcomboCategory);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.enumcomboCategory]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
