
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz
{
	public partial class CounterpartyDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.RadioButton radioInfo;
		
		private global::Gtk.RadioButton radioContacts;
		
		private global::Gtk.RadioButton radioDetails;
		
		private global::Gtk.RadioButton radioCurators;
		
		private global::Gtk.RadioButton radioContactPersons;
		
		private global::Gtk.RadioButton radiobuttonProxies;
		
		private global::Gtk.RadioButton radioContracts;
		
		private global::Gtk.RadioButton radioDeliveryPoint;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.DataBindings.DataTable datatable1;
		
		private global::Gtk.DataBindings.DataEntry entryFullName;
		
		private global::Gtk.DataBindings.DataEntry entryName;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumCounterpartyType;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumPayment;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumPersonType;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow6;
		
		private global::Gtk.DataBindings.DataTextView dataComment;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		
		private global::Gtk.DataBindings.DataTextView dataWaybillComment;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.DataBindings.DataEntryReference referenceMainCounterparty;
		
		private global::Gtk.DataBindings.DataEntryReference referenceSignificance;
		
		private global::Gtk.DataBindings.DataEntryReference referenceStatus;
		
		private global::Gtk.DataBindings.DataSpinButton spinMaxCredit;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.DataBindings.DataTable datatable2;
		
		private global::Gtk.DataBindings.DataEntryReference dataentryFinancialContact;
		
		private global::Gtk.DataBindings.DataEntryReference dataentryMainContact;
		
		private global::QSContacts.EmailsView emailsView;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label18;
		
		private global::QSContacts.PhonesView phonesView;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.DataBindings.DataTable datatable4;
		
		private global::Gtk.DataBindings.DataEntry entryJurAddress;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Label label29;
		
		private global::QSOrmProject.DataValidatedEntry validatedINN;
		
		private global::QSOrmProject.DataValidatedEntry validatedKPP;
		
		private global::QSBanks.AccountsView accountsView;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.DataBindings.DataTable datatable3;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.DataBindings.DataEntryReference referenceAccountant;
		
		private global::Gtk.DataBindings.DataEntryReference referenceBottleManager;
		
		private global::Gtk.DataBindings.DataEntryReference referenceSalesManager;
		
		private global::Gtk.Label label10;
		
		private global::Vodovoz.ContactsView contactsview1;
		
		private global::Gtk.Label label24;
		
		private global::Vodovoz.ProxyView proxiesview1;
		
		private global::Gtk.Label label30;
		
		private global::Vodovoz.CounterpartyContractsView counterpartyContractsView;
		
		private global::Gtk.Label label34;
		
		private global::Gtk.VBox vbox9;
		
		private global::Vodovoz.DeliveryPointView deliveryPointView;
		
		private global::Gtk.Label label40;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Vodovoz.CounterpartyDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Vodovoz.CounterpartyDlg";
			// Container child Vodovoz.CounterpartyDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.HeightRequest = 400;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отмена");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioInfo = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Информация"));
			this.radioInfo.CanFocus = true;
			this.radioInfo.Name = "radioInfo";
			this.radioInfo.DrawIndicator = false;
			this.radioInfo.UseUnderline = true;
			this.radioInfo.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox19.Add (this.radioInfo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioInfo]));
			w7.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContacts = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Контакты"));
			this.radioContacts.CanFocus = true;
			this.radioContacts.Name = "radioContacts";
			this.radioContacts.DrawIndicator = false;
			this.radioContacts.UseUnderline = true;
			this.radioContacts.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContacts);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContacts]));
			w8.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioDetails = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Реквизиты"));
			this.radioDetails.CanFocus = true;
			this.radioDetails.Name = "radioDetails";
			this.radioDetails.DrawIndicator = false;
			this.radioDetails.UseUnderline = true;
			this.radioDetails.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioDetails);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioDetails]));
			w9.Position = 2;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioCurators = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Кураторы"));
			this.radioCurators.CanFocus = true;
			this.radioCurators.Name = "radioCurators";
			this.radioCurators.DrawIndicator = false;
			this.radioCurators.UseUnderline = true;
			this.radioCurators.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioCurators);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioCurators]));
			w10.Position = 3;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContactPersons = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Контактные лица"));
			this.radioContactPersons.CanFocus = true;
			this.radioContactPersons.Name = "radioContactPersons";
			this.radioContactPersons.DrawIndicator = false;
			this.radioContactPersons.UseUnderline = true;
			this.radioContactPersons.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContactPersons);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContactPersons]));
			w11.Position = 4;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radiobuttonProxies = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Доверенности"));
			this.radiobuttonProxies.CanFocus = true;
			this.radiobuttonProxies.Name = "radiobuttonProxies";
			this.radiobuttonProxies.DrawIndicator = false;
			this.radiobuttonProxies.UseUnderline = true;
			this.radiobuttonProxies.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radiobuttonProxies);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radiobuttonProxies]));
			w12.Position = 5;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContracts = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Договор"));
			this.radioContracts.CanFocus = true;
			this.radioContracts.Name = "radioContracts";
			this.radioContracts.DrawIndicator = false;
			this.radioContracts.UseUnderline = true;
			this.radioContracts.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContracts);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContracts]));
			w13.Position = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioDeliveryPoint = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Точки доставки"));
			this.radioDeliveryPoint.CanFocus = true;
			this.radioDeliveryPoint.Name = "radioDeliveryPoint";
			this.radioDeliveryPoint.DrawIndicator = false;
			this.radioDeliveryPoint.UseUnderline = true;
			this.radioDeliveryPoint.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioDeliveryPoint);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioDeliveryPoint]));
			w14.Position = 7;
			this.vbox2.Add (this.hbox19);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox19]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 4;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			global::Gtk.Viewport w16 = new global::Gtk.Viewport ();
			w16.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(10)), ((uint)(2)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(6));
			this.datatable1.ColumnSpacing = ((uint)(6));
			this.datatable1.BorderWidth = ((uint)(6));
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			// Container child datatable1.Gtk.Table+TableChild
			this.entryFullName = new global::Gtk.DataBindings.DataEntry ();
			this.entryFullName.CanFocus = true;
			this.entryFullName.Name = "entryFullName";
			this.entryFullName.IsEditable = true;
			this.entryFullName.InvisibleChar = '●';
			this.entryFullName.InheritedDataSource = true;
			this.entryFullName.Mappings = "FullName";
			this.entryFullName.InheritedBoundaryDataSource = false;
			this.entryFullName.InheritedDataSource = true;
			this.entryFullName.Mappings = "FullName";
			this.entryFullName.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.entryFullName);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.entryFullName]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.entryName = new global::Gtk.DataBindings.DataEntry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.entryName.InheritedDataSource = true;
			this.entryName.Mappings = "Name";
			this.entryName.InheritedBoundaryDataSource = false;
			this.entryName.InheritedDataSource = true;
			this.entryName.Mappings = "Name";
			this.entryName.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.entryName);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.entryName]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumCounterpartyType = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumCounterpartyType.Name = "enumCounterpartyType";
			this.enumCounterpartyType.InheritedBoundaryDataSource = false;
			this.enumCounterpartyType.InheritedDataSource = true;
			this.enumCounterpartyType.Mappings = "CounterpartyType";
			this.enumCounterpartyType.InheritedBoundaryDataSource = false;
			this.enumCounterpartyType.InheritedDataSource = true;
			this.enumCounterpartyType.Mappings = "CounterpartyType";
			this.datatable1.Add (this.enumCounterpartyType);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumCounterpartyType]));
			w19.TopAttach = ((uint)(6));
			w19.BottomAttach = ((uint)(7));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumPayment = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumPayment.Name = "enumPayment";
			this.enumPayment.InheritedBoundaryDataSource = false;
			this.enumPayment.InheritedDataSource = false;
			this.enumPayment.Mappings = "PaymentMethod";
			this.enumPayment.InheritedBoundaryDataSource = false;
			this.enumPayment.InheritedDataSource = false;
			this.enumPayment.Mappings = "PaymentMethod";
			this.datatable1.Add (this.enumPayment);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumPayment]));
			w20.TopAttach = ((uint)(7));
			w20.BottomAttach = ((uint)(8));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumPersonType = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumPersonType.Name = "enumPersonType";
			this.enumPersonType.InheritedBoundaryDataSource = false;
			this.enumPersonType.InheritedDataSource = true;
			this.enumPersonType.Mappings = "PersonType";
			this.enumPersonType.InheritedBoundaryDataSource = false;
			this.enumPersonType.InheritedDataSource = true;
			this.enumPersonType.Mappings = "PersonType";
			this.datatable1.Add (this.enumPersonType);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumPersonType]));
			w21.TopAttach = ((uint)(5));
			w21.BottomAttach = ((uint)(6));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.dataComment = new global::Gtk.DataBindings.DataTextView ();
			this.dataComment.CanFocus = true;
			this.dataComment.Name = "dataComment";
			this.dataComment.Editable = false;
			this.dataComment.InheritedDataSource = true;
			this.dataComment.Mappings = "Comment";
			this.dataComment.InheritedBoundaryDataSource = false;
			this.dataComment.InheritedDataSource = true;
			this.dataComment.Mappings = "Comment";
			this.dataComment.InheritedBoundaryDataSource = false;
			this.GtkScrolledWindow6.Add (this.dataComment);
			this.hbox18.Add (this.GtkScrolledWindow6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.GtkScrolledWindow6]));
			w23.Position = 0;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий\nдля накладной:");
			this.label25.Justify = ((global::Gtk.Justification)(1));
			this.hbox18.Add (this.label25);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label25]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(5));
			// Container child hbox18.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.dataWaybillComment = new global::Gtk.DataBindings.DataTextView ();
			this.dataWaybillComment.CanFocus = true;
			this.dataWaybillComment.Name = "dataWaybillComment";
			this.dataWaybillComment.Editable = false;
			this.dataWaybillComment.InheritedDataSource = true;
			this.dataWaybillComment.Mappings = "WaybillComment";
			this.dataWaybillComment.InheritedBoundaryDataSource = false;
			this.dataWaybillComment.InheritedDataSource = true;
			this.dataWaybillComment.Mappings = "WaybillComment";
			this.dataWaybillComment.InheritedBoundaryDataSource = false;
			this.GtkScrolledWindow5.Add (this.dataWaybillComment);
			this.hbox18.Add (this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.GtkScrolledWindow5]));
			w26.Position = 2;
			this.datatable1.Add (this.hbox18);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.hbox18]));
			w27.TopAttach = ((uint)(9));
			w27.BottomAttach = ((uint)(10));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Полное наименование:");
			this.datatable1.Add (this.label16);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label16]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Наименование:");
			this.datatable1.Add (this.label17);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label17]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString (" Максимальная\nсумма кредита:");
			this.datatable1.Add (this.label19);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label19]));
			w30.TopAttach = ((uint)(8));
			w30.BottomAttach = ((uint)(9));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.Xalign = 1F;
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("  Форма оплаты \n(по умолчанию):");
			this.datatable1.Add (this.label26);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label26]));
			w31.TopAttach = ((uint)(7));
			w31.BottomAttach = ((uint)(8));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.Xalign = 1F;
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.datatable1.Add (this.label31);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label31]));
			w32.TopAttach = ((uint)(9));
			w32.BottomAttach = ((uint)(10));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Статус:");
			this.datatable1.Add (this.label5);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label5]));
			w33.TopAttach = ((uint)(3));
			w33.BottomAttach = ((uint)(4));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Значимость:");
			this.datatable1.Add (this.label6);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label6]));
			w34.TopAttach = ((uint)(4));
			w34.BottomAttach = ((uint)(5));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Головная организация:");
			this.datatable1.Add (this.label7);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label7]));
			w35.TopAttach = ((uint)(2));
			w35.BottomAttach = ((uint)(3));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Форма контрагента:");
			this.datatable1.Add (this.label8);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label8]));
			w36.TopAttach = ((uint)(5));
			w36.BottomAttach = ((uint)(6));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип контрагента:");
			this.datatable1.Add (this.label9);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label9]));
			w37.TopAttach = ((uint)(6));
			w37.BottomAttach = ((uint)(7));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceMainCounterparty = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceMainCounterparty.Events = ((global::Gdk.EventMask)(256));
			this.referenceMainCounterparty.Name = "referenceMainCounterparty";
			this.referenceMainCounterparty.DisplayFields = new string[] {
				"Name"
			};
			this.referenceMainCounterparty.InheritedDataSource = true;
			this.referenceMainCounterparty.Mappings = "MainCounterparty";
			this.referenceMainCounterparty.InheritedBoundaryDataSource = false;
			this.referenceMainCounterparty.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceMainCounterparty);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceMainCounterparty]));
			w38.TopAttach = ((uint)(2));
			w38.BottomAttach = ((uint)(3));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceSignificance = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceSignificance.Events = ((global::Gdk.EventMask)(256));
			this.referenceSignificance.Name = "referenceSignificance";
			this.referenceSignificance.DisplayFields = new string[] {
				"Name"
			};
			this.referenceSignificance.InheritedDataSource = true;
			this.referenceSignificance.Mappings = "Significance";
			this.referenceSignificance.InheritedBoundaryDataSource = false;
			this.referenceSignificance.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceSignificance);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceSignificance]));
			w39.TopAttach = ((uint)(4));
			w39.BottomAttach = ((uint)(5));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceStatus = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceStatus.Events = ((global::Gdk.EventMask)(256));
			this.referenceStatus.Name = "referenceStatus";
			this.referenceStatus.DisplayFields = new string[] {
				"Name"
			};
			this.referenceStatus.InheritedDataSource = true;
			this.referenceStatus.Mappings = "Status";
			this.referenceStatus.InheritedBoundaryDataSource = false;
			this.referenceStatus.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceStatus);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceStatus]));
			w40.TopAttach = ((uint)(3));
			w40.BottomAttach = ((uint)(4));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.spinMaxCredit = new global::Gtk.DataBindings.DataSpinButton (0, 1000000, 100);
			this.spinMaxCredit.CanFocus = true;
			this.spinMaxCredit.Name = "spinMaxCredit";
			this.spinMaxCredit.Adjustment.PageIncrement = 10;
			this.spinMaxCredit.ClimbRate = 1;
			this.spinMaxCredit.Numeric = true;
			this.spinMaxCredit.InheritedDataSource = true;
			this.spinMaxCredit.Mappings = "MaxCredit";
			this.spinMaxCredit.InheritedBoundaryDataSource = false;
			this.spinMaxCredit.InheritedDataSource = true;
			this.spinMaxCredit.Mappings = "MaxCredit";
			this.spinMaxCredit.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.spinMaxCredit);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.spinMaxCredit]));
			w41.TopAttach = ((uint)(8));
			w41.BottomAttach = ((uint)(9));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			w16.Add (this.datatable1);
			this.GtkScrolledWindow4.Add (w16);
			this.notebook1.Add (this.GtkScrolledWindow4);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow4, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.datatable2 = new global::Gtk.DataBindings.DataTable (((uint)(4)), ((uint)(2)), false);
			this.datatable2.Name = "datatable2";
			this.datatable2.RowSpacing = ((uint)(6));
			this.datatable2.ColumnSpacing = ((uint)(6));
			this.datatable2.BorderWidth = ((uint)(6));
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			// Container child datatable2.Gtk.Table+TableChild
			this.dataentryFinancialContact = new global::Gtk.DataBindings.DataEntryReference ();
			this.dataentryFinancialContact.Events = ((global::Gdk.EventMask)(256));
			this.dataentryFinancialContact.Name = "dataentryFinancialContact";
			this.dataentryFinancialContact.DisplayFields = new string[] {
				"FullName"
			};
			this.dataentryFinancialContact.InheritedDataSource = true;
			this.dataentryFinancialContact.Mappings = "FinancialContact";
			this.dataentryFinancialContact.InheritedBoundaryDataSource = false;
			this.dataentryFinancialContact.CursorPointsEveryType = false;
			this.datatable2.Add (this.dataentryFinancialContact);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.dataentryFinancialContact]));
			w45.TopAttach = ((uint)(3));
			w45.BottomAttach = ((uint)(4));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.dataentryMainContact = new global::Gtk.DataBindings.DataEntryReference ();
			this.dataentryMainContact.Events = ((global::Gdk.EventMask)(256));
			this.dataentryMainContact.Name = "dataentryMainContact";
			this.dataentryMainContact.DisplayFields = new string[] {
				"FullName",
				"MainPhoneString"
			};
			this.dataentryMainContact.DisplayFormatString = "{0}; телефон: {1}";
			this.dataentryMainContact.InheritedDataSource = true;
			this.dataentryMainContact.Mappings = "MainContact";
			this.dataentryMainContact.InheritedBoundaryDataSource = false;
			this.dataentryMainContact.CursorPointsEveryType = false;
			this.datatable2.Add (this.dataentryMainContact);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.dataentryMainContact]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.emailsView = new global::QSContacts.EmailsView ();
			this.emailsView.Events = ((global::Gdk.EventMask)(256));
			this.emailsView.Name = "emailsView";
			this.datatable2.Add (this.emailsView);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.emailsView]));
			w47.TopAttach = ((uint)(1));
			w47.BottomAttach = ((uint)(2));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Общий e-mail:");
			this.datatable2.Add (this.label11);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label11]));
			w48.TopAttach = ((uint)(1));
			w48.BottomAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Главное контактное лицо:");
			this.datatable2.Add (this.label12);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label12]));
			w49.TopAttach = ((uint)(2));
			w49.BottomAttach = ((uint)(3));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Контактное лицо по \nфинансовым вопросам:");
			this.label13.UseMarkup = true;
			this.datatable2.Add (this.label13);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label13]));
			w50.TopAttach = ((uint)(3));
			w50.BottomAttach = ((uint)(4));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Общие телефоны:");
			this.datatable2.Add (this.label18);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label18]));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.phonesView = new global::QSContacts.PhonesView ();
			this.phonesView.Events = ((global::Gdk.EventMask)(256));
			this.phonesView.Name = "phonesView";
			this.datatable2.Add (this.phonesView);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.phonesView]));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.datatable2);
			global::Gtk.Notebook.NotebookChild w53 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.datatable2]));
			w53.Position = 1;
			// Notebook tab
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Контакты");
			this.notebook1.SetTabLabel (this.datatable2, this.label20);
			this.label20.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(6));
			// Container child vbox6.Gtk.Box+BoxChild
			this.datatable4 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
			this.datatable4.Name = "datatable4";
			this.datatable4.RowSpacing = ((uint)(6));
			this.datatable4.ColumnSpacing = ((uint)(6));
			this.datatable4.InheritedDataSource = false;
			this.datatable4.InheritedBoundaryDataSource = false;
			this.datatable4.InheritedDataSource = false;
			this.datatable4.InheritedBoundaryDataSource = false;
			// Container child datatable4.Gtk.Table+TableChild
			this.entryJurAddress = new global::Gtk.DataBindings.DataEntry ();
			this.entryJurAddress.CanFocus = true;
			this.entryJurAddress.Name = "entryJurAddress";
			this.entryJurAddress.IsEditable = true;
			this.entryJurAddress.InvisibleChar = '●';
			this.entryJurAddress.InheritedDataSource = true;
			this.entryJurAddress.Mappings = "JurAddress";
			this.entryJurAddress.InheritedBoundaryDataSource = false;
			this.entryJurAddress.InheritedDataSource = true;
			this.entryJurAddress.Mappings = "JurAddress";
			this.entryJurAddress.InheritedBoundaryDataSource = false;
			this.datatable4.Add (this.entryJurAddress);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.entryJurAddress]));
			w54.TopAttach = ((uint)(2));
			w54.BottomAttach = ((uint)(3));
			w54.LeftAttach = ((uint)(1));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.Xalign = 1F;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("ИНН:");
			this.datatable4.Add (this.label27);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label27]));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.Xalign = 1F;
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("КПП:");
			this.datatable4.Add (this.label28);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label28]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.Xalign = 1F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Юр. адрес:");
			this.datatable4.Add (this.label29);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label29]));
			w57.TopAttach = ((uint)(2));
			w57.BottomAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedINN = new global::QSOrmProject.DataValidatedEntry ();
			this.validatedINN.CanFocus = true;
			this.validatedINN.Name = "validatedINN";
			this.validatedINN.IsEditable = true;
			this.validatedINN.InvisibleChar = '●';
			this.validatedINN.InheritedDataSource = true;
			this.validatedINN.Mappings = "INN";
			this.validatedINN.InheritedBoundaryDataSource = false;
			this.datatable4.Add (this.validatedINN);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedINN]));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedKPP = new global::QSOrmProject.DataValidatedEntry ();
			this.validatedKPP.CanFocus = true;
			this.validatedKPP.Name = "validatedKPP";
			this.validatedKPP.IsEditable = true;
			this.validatedKPP.InvisibleChar = '●';
			this.validatedKPP.InheritedDataSource = true;
			this.validatedKPP.Mappings = "KPP";
			this.validatedKPP.InheritedBoundaryDataSource = false;
			this.datatable4.Add (this.validatedKPP);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedKPP]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.datatable4);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.datatable4]));
			w60.Position = 0;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.accountsView = new global::QSBanks.AccountsView ();
			this.accountsView.Events = ((global::Gdk.EventMask)(256));
			this.accountsView.Name = "accountsView";
			this.vbox6.Add (this.accountsView);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.accountsView]));
			w61.Position = 1;
			this.notebook1.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w62 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
			w62.Position = 2;
			// Notebook tab
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Реквизиты");
			this.notebook1.SetTabLabel (this.vbox6, this.label21);
			this.label21.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.datatable3 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
			this.datatable3.Name = "datatable3";
			this.datatable3.RowSpacing = ((uint)(6));
			this.datatable3.ColumnSpacing = ((uint)(6));
			this.datatable3.BorderWidth = ((uint)(6));
			this.datatable3.InheritedDataSource = false;
			this.datatable3.InheritedBoundaryDataSource = false;
			this.datatable3.InheritedDataSource = false;
			this.datatable3.InheritedBoundaryDataSource = false;
			// Container child datatable3.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Менеджер по продажам:");
			this.datatable3.Add (this.label14);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label14]));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Бухгалтер:");
			this.datatable3.Add (this.label22);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label22]));
			w64.TopAttach = ((uint)(1));
			w64.BottomAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 1F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Менеджер по бутылям:");
			this.datatable3.Add (this.label23);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label23]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.referenceAccountant = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceAccountant.Events = ((global::Gdk.EventMask)(256));
			this.referenceAccountant.Name = "referenceAccountant";
			this.referenceAccountant.DisplayFields = new string[] {
				"LastName",
				"Name",
				"Patronymic"
			};
			this.referenceAccountant.DisplayFormatString = "{0} {1} {2}";
			this.referenceAccountant.InheritedDataSource = true;
			this.referenceAccountant.Mappings = "Accountant";
			this.referenceAccountant.InheritedBoundaryDataSource = false;
			this.referenceAccountant.CursorPointsEveryType = false;
			this.datatable3.Add (this.referenceAccountant);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.referenceAccountant]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.referenceBottleManager = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceBottleManager.Events = ((global::Gdk.EventMask)(256));
			this.referenceBottleManager.Name = "referenceBottleManager";
			this.referenceBottleManager.DisplayFields = new string[] {
				"LastName",
				"Name",
				"Patronymic"
			};
			this.referenceBottleManager.DisplayFormatString = "{0} {1} {2}";
			this.referenceBottleManager.InheritedDataSource = true;
			this.referenceBottleManager.Mappings = "BottlesManager";
			this.referenceBottleManager.InheritedBoundaryDataSource = false;
			this.referenceBottleManager.CursorPointsEveryType = false;
			this.datatable3.Add (this.referenceBottleManager);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.referenceBottleManager]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.LeftAttach = ((uint)(1));
			w67.RightAttach = ((uint)(2));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.referenceSalesManager = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceSalesManager.Events = ((global::Gdk.EventMask)(256));
			this.referenceSalesManager.Name = "referenceSalesManager";
			this.referenceSalesManager.DisplayFields = new string[] {
				"LastName",
				"Name",
				"Patronymic"
			};
			this.referenceSalesManager.DisplayFormatString = "{0} {1} {2}";
			this.referenceSalesManager.InheritedDataSource = true;
			this.referenceSalesManager.Mappings = "SalesManager";
			this.referenceSalesManager.InheritedBoundaryDataSource = false;
			this.referenceSalesManager.CursorPointsEveryType = false;
			this.datatable3.Add (this.referenceSalesManager);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.referenceSalesManager]));
			w68.LeftAttach = ((uint)(1));
			w68.RightAttach = ((uint)(2));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.datatable3);
			global::Gtk.Notebook.NotebookChild w69 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.datatable3]));
			w69.Position = 3;
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Кураторы");
			this.notebook1.SetTabLabel (this.datatable3, this.label10);
			this.label10.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.contactsview1 = new global::Vodovoz.ContactsView ();
			this.contactsview1.Events = ((global::Gdk.EventMask)(256));
			this.contactsview1.Name = "contactsview1";
			this.notebook1.Add (this.contactsview1);
			global::Gtk.Notebook.NotebookChild w70 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.contactsview1]));
			w70.Position = 4;
			// Notebook tab
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Контактные лица");
			this.notebook1.SetTabLabel (this.contactsview1, this.label24);
			this.label24.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.proxiesview1 = new global::Vodovoz.ProxyView ();
			this.proxiesview1.Events = ((global::Gdk.EventMask)(256));
			this.proxiesview1.Name = "proxiesview1";
			this.notebook1.Add (this.proxiesview1);
			global::Gtk.Notebook.NotebookChild w71 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.proxiesview1]));
			w71.Position = 5;
			// Notebook tab
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Доверенности");
			this.notebook1.SetTabLabel (this.proxiesview1, this.label30);
			this.label30.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.counterpartyContractsView = new global::Vodovoz.CounterpartyContractsView ();
			this.counterpartyContractsView.Events = ((global::Gdk.EventMask)(256));
			this.counterpartyContractsView.Name = "counterpartyContractsView";
			this.notebook1.Add (this.counterpartyContractsView);
			global::Gtk.Notebook.NotebookChild w72 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.counterpartyContractsView]));
			w72.Position = 6;
			// Notebook tab
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("Договор");
			this.notebook1.SetTabLabel (this.counterpartyContractsView, this.label34);
			this.label34.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			this.vbox9.BorderWidth = ((uint)(6));
			// Container child vbox9.Gtk.Box+BoxChild
			this.deliveryPointView = new global::Vodovoz.DeliveryPointView ();
			this.deliveryPointView.Events = ((global::Gdk.EventMask)(256));
			this.deliveryPointView.Name = "deliveryPointView";
			this.vbox9.Add (this.deliveryPointView);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.deliveryPointView]));
			w73.Position = 0;
			this.notebook1.Add (this.vbox9);
			global::Gtk.Notebook.NotebookChild w74 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox9]));
			w74.Position = 7;
			// Notebook tab
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("Точки доставки");
			this.notebook1.SetTabLabel (this.vbox9, this.label40);
			this.label40.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w75.Position = 3;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.radioInfo.Toggled += new global::System.EventHandler (this.OnRadioInfoToggled);
			this.radioContacts.Toggled += new global::System.EventHandler (this.OnRadioContactsToggled);
			this.radioDetails.Toggled += new global::System.EventHandler (this.OnRadioDetailsToggled);
			this.radioCurators.Toggled += new global::System.EventHandler (this.OnRadioCuratorsToggled);
			this.radioContactPersons.Toggled += new global::System.EventHandler (this.OnRadioContactPersonsToggled);
			this.radiobuttonProxies.Toggled += new global::System.EventHandler (this.OnRadiobuttonProxiesToggled);
			this.radioContracts.Toggled += new global::System.EventHandler (this.OnRadioContractsToggled);
			this.radioDeliveryPoint.Toggled += new global::System.EventHandler (this.OnRadioDeliveryPointToggled);
		}
	}
}
