
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz
{
	public partial class MovementDocumentDlg
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Vodovoz.MovementDocumentDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Vodovoz.MovementDocumentDlg";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
