
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Complaints
{
	public partial class ComplaintDiscussionView
	{
		private global::Gtk.VBox vboxWidget;

		private global::Gtk.HBox hboxInfo;

		private global::Gamma.GtkWidgets.yLabel ylabelSubdivision;

		private global::Gtk.HBox hboxFields;

		private global::Gtk.Label labelPlannedCompletionDate;

		private global::Gamma.Widgets.yDatePicker ydatepickerPlannedCompletionDate;

		private global::Gtk.Label labelStatus;

		private global::Gamma.Widgets.yEnumComboBox yenumcomboStatus;

		private global::Gtk.Label labelComments;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewComments;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTextView ytextviewComment;

		private global::Gtk.HBox hboxButtons;

		private global::Gamma.GtkWidgets.yButton ybuttonAddComment;

		private global::Gamma.GtkWidgets.yButton ybuttonAddFiles;

		private global::Gamma.GtkWidgets.yButton ybuttonClearFiles;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Complaints.ComplaintDiscussionView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Complaints.ComplaintDiscussionView";
			// Container child Vodovoz.Views.Complaints.ComplaintDiscussionView.Gtk.Container+ContainerChild
			this.vboxWidget = new global::Gtk.VBox();
			this.vboxWidget.Name = "vboxWidget";
			this.vboxWidget.Spacing = 6;
			// Container child vboxWidget.Gtk.Box+BoxChild
			this.hboxInfo = new global::Gtk.HBox();
			this.hboxInfo.Name = "hboxInfo";
			this.hboxInfo.Spacing = 6;
			// Container child hboxInfo.Gtk.Box+BoxChild
			this.ylabelSubdivision = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelSubdivision.Name = "ylabelSubdivision";
			this.ylabelSubdivision.LabelProp = global::Mono.Unix.Catalog.GetString("###");
			this.ylabelSubdivision.UseMarkup = true;
			this.hboxInfo.Add(this.ylabelSubdivision);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxInfo[this.ylabelSubdivision]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxInfo.Gtk.Box+BoxChild
			this.hboxFields = new global::Gtk.HBox();
			this.hboxFields.Name = "hboxFields";
			this.hboxFields.Spacing = 6;
			// Container child hboxFields.Gtk.Box+BoxChild
			this.labelPlannedCompletionDate = new global::Gtk.Label();
			this.labelPlannedCompletionDate.Name = "labelPlannedCompletionDate";
			this.labelPlannedCompletionDate.LabelProp = global::Mono.Unix.Catalog.GetString("Дата план. завер.:");
			this.hboxFields.Add(this.labelPlannedCompletionDate);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxFields[this.labelPlannedCompletionDate]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxFields.Gtk.Box+BoxChild
			this.ydatepickerPlannedCompletionDate = new global::Gamma.Widgets.yDatePicker();
			this.ydatepickerPlannedCompletionDate.Events = ((global::Gdk.EventMask)(256));
			this.ydatepickerPlannedCompletionDate.Name = "ydatepickerPlannedCompletionDate";
			this.ydatepickerPlannedCompletionDate.WithTime = false;
			this.ydatepickerPlannedCompletionDate.Date = new global::System.DateTime(0);
			this.ydatepickerPlannedCompletionDate.IsEditable = true;
			this.ydatepickerPlannedCompletionDate.AutoSeparation = false;
			this.hboxFields.Add(this.ydatepickerPlannedCompletionDate);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxFields[this.ydatepickerPlannedCompletionDate]));
			w3.Position = 1;
			// Container child hboxFields.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Статус:");
			this.hboxFields.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxFields[this.labelStatus]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxFields.Gtk.Box+BoxChild
			this.yenumcomboStatus = new global::Gamma.Widgets.yEnumComboBox();
			this.yenumcomboStatus.Name = "yenumcomboStatus";
			this.yenumcomboStatus.ShowSpecialStateAll = false;
			this.yenumcomboStatus.ShowSpecialStateNot = false;
			this.yenumcomboStatus.UseShortTitle = false;
			this.yenumcomboStatus.DefaultFirst = false;
			this.hboxFields.Add(this.yenumcomboStatus);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxFields[this.yenumcomboStatus]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.hboxInfo.Add(this.hboxFields);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxInfo[this.hboxFields]));
			w6.Position = 2;
			this.vboxWidget.Add(this.hboxInfo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxWidget[this.hboxInfo]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxWidget.Gtk.Box+BoxChild
			this.labelComments = new global::Gtk.Label();
			this.labelComments.Name = "labelComments";
			this.labelComments.Xalign = 0F;
			this.labelComments.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарии:");
			this.vboxWidget.Add(this.labelComments);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxWidget[this.labelComments]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxWidget.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeviewComments = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewComments.CanFocus = true;
			this.ytreeviewComments.Name = "ytreeviewComments";
			this.GtkScrolledWindow.Add(this.ytreeviewComments);
			this.vboxWidget.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxWidget[this.GtkScrolledWindow]));
			w10.Position = 2;
			// Container child vboxWidget.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.HeightRequest = 70;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ytextviewComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytextviewComment.CanFocus = true;
			this.ytextviewComment.Name = "ytextviewComment";
			this.GtkScrolledWindow1.Add(this.ytextviewComment);
			this.vboxWidget.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxWidget[this.GtkScrolledWindow1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxWidget.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.ybuttonAddComment = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonAddComment.CanFocus = true;
			this.ybuttonAddComment.Name = "ybuttonAddComment";
			this.ybuttonAddComment.UseUnderline = true;
			this.ybuttonAddComment.Label = global::Mono.Unix.Catalog.GetString("Добавить комментарий");
			this.hboxButtons.Add(this.ybuttonAddComment);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.ybuttonAddComment]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.ybuttonAddFiles = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonAddFiles.CanFocus = true;
			this.ybuttonAddFiles.Name = "ybuttonAddFiles";
			this.ybuttonAddFiles.UseUnderline = true;
			this.ybuttonAddFiles.Label = global::Mono.Unix.Catalog.GetString("Прикрепить файлы");
			this.hboxButtons.Add(this.ybuttonAddFiles);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.ybuttonAddFiles]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.ybuttonClearFiles = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonClearFiles.CanFocus = true;
			this.ybuttonClearFiles.Name = "ybuttonClearFiles";
			this.ybuttonClearFiles.UseUnderline = true;
			this.ybuttonClearFiles.Label = global::Mono.Unix.Catalog.GetString("Удалить файлы");
			this.hboxButtons.Add(this.ybuttonClearFiles);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.ybuttonClearFiles]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vboxWidget.Add(this.hboxButtons);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxWidget[this.hboxButtons]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vboxWidget);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
