
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz
{
	public partial class EmployeeDlg
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.RadioButton radioTabInfo;

		private global::Gtk.RadioButton radioTabLogistic;

		private global::Gtk.RadioButton radioTabAccounting;

		private global::Gtk.RadioButton radioTabFiles;

		private global::Gtk.RadioButton radioTabContracts;

		private global::Gtk.RadioButton radioTabEmployeeDocument;

		private global::Gtk.RadioButton radioWageParameters;

		private global::Gtk.Notebook notebookMain;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Table datatableMain;

		private global::Gamma.GtkWidgets.yCheckButton checkbuttonRussianCitizen;

		private global::Gamma.Widgets.yEnumComboBox comboCategory;

		private global::Gamma.GtkWidgets.yEntry dataentryInnerPhone;

		private global::Gamma.GtkWidgets.yEntry dataentryLastName;

		private global::Gamma.GtkWidgets.yEntry dataentryName;

		private global::Gamma.GtkWidgets.yEntry dataentryPatronymic;

		private global::Gtk.HBox datahbox3;

		private global::Gtk.Label label16;

		private global::QS.Widgets.GtkUI.DatePicker ydateFirstWorkDay;

		private global::Gamma.GtkWidgets.yLabel ylabel2;

		private global::QS.Widgets.GtkUI.DatePicker dateHired;

		private global::Gamma.GtkWidgets.yLabel ylabel3;

		private global::QS.Widgets.GtkUI.DatePicker dateFired;

		private global::Gamma.GtkWidgets.yLabel ylabel4;

		private global::QS.Widgets.GtkUI.DatePicker dateCalculated;

		private global::Gamma.GtkWidgets.yEntry entryAddressCurrent;

		private global::Gamma.GtkWidgets.yEntry entryAddressRegistration;

		private global::Gtk.HBox hbox14;

		private global::Gamma.GtkWidgets.yLabel ylblUserLogin;

		private global::Gamma.Widgets.yValidatedEntry yentryUserLogin;

		private global::Gtk.HBox hboxDriversParameters;

		private global::Gamma.Widgets.yEnumComboBox cmbDriverOf;

		private global::Gamma.GtkWidgets.yCheckButton checkVisitingMaster;

		private global::Gamma.GtkWidgets.yCheckButton chkDriverForOneDay;

		private global::Gamma.GtkWidgets.yCheckButton checkChainStoreDriver;

		private global::Gtk.HBox hboxSubdivision;

		private global::Gtk.Label label10;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label18;

		private global::Gtk.Label label2;

		private global::Gtk.Label Label20_InnerPhone;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelCitizenship;

		private global::Gtk.Label lblDriverOf;

		private global::Vodovoz.Views.Contacts.PhonesView phonesView;

		private global::QS.Widgets.GtkUI.PhotoView photoviewEmployee;

		private global::Gamma.Widgets.yEntryReference referenceCitizenship;

		private global::Gamma.Widgets.yEntryReference referenceNationality;

		private global::Gamma.Widgets.yEntryReference referenceUser;

		private global::QS.Widgets.GtkUI.DatePicker ydatepicker1;

		private global::Gamma.Widgets.yEnumComboBox yenumcombobox13;

		private global::Gamma.Widgets.yEnumComboBox yenumcomboStatus;

		private global::Gamma.GtkWidgets.yLabel ylabel5;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vboxPageLogistic;

		private global::Gtk.Table table1;

		private global::Gamma.Widgets.yEnumComboBox comboDriverType;

		private global::Gamma.GtkWidgets.yEntry dataentryAndroidLogin;

		private global::Gamma.GtkWidgets.yEntry dataentryAndroidPassword;

		private global::Gamma.GtkWidgets.yEntry dataentryDrivingNumber;

		private global::Gtk.HBox hbox8;

		private global::Gamma.GtkWidgets.ySpinButton yspinDriverSpeed;

		private global::Gtk.Label label23;

		private global::Gtk.Label label11;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label26;

		private global::Gtk.Label label27;

		private global::Gtk.Label label28;

		private global::Gtk.Label labelAndroid;

		private global::Gtk.Label labelAndroidPassword;

		private global::Gamma.GtkWidgets.ySpinButton maxAddressesSpin;

		private global::Gamma.GtkWidgets.ySpinButton minAddressesSpin;

		private global::QS.Widgets.GtkUI.RepresentationEntry repEntDefaultForwarder;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.ySpinButton yspinTripsPriority;

		private global::Gtk.Label label29;

		private global::Gtk.ScrolledWindow GtkScrolledWindow6;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewDriverSchedule;

		private global::Gtk.Label label25;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewDistricts;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button buttonAddDistrict;

		private global::Gtk.Button buttonRemoveDistrict;

		private global::Gtk.Label label12;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label19;

		private global::Gamma.GtkWidgets.yEntry entryInn;

		private global::QSBanks.AccountsView accountsView;

		private global::Gtk.Label label17;

		private global::QSAttachment.Attachment attachmentFiles;

		private global::Gtk.Label label24;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Button button53;

		private global::Gtk.Button buttonContractEdit;

		private global::Gtk.Button button55;

		private global::Gtk.ScrolledWindow GtkScrolledWindow5;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewEmployeeContract;

		private global::Gtk.Label lable66;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Button buttonAddDocument;

		private global::Gtk.Button buttonDocumentEdit;

		private global::Gtk.Button button3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow4;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewEmployeeDocument;

		private global::Gtk.Label label30;

		private global::Vodovoz.Views.WageCalculation.EmployeeWageParametersView wageParametersView;

		private global::Gtk.Label labelWageParameters;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.EmployeeDlg
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.EmployeeDlg";
			// Container child Vodovoz.EmployeeDlg.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabInfo = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Основное"));
			this.radioTabInfo.CanFocus = true;
			this.radioTabInfo.Name = "radioTabInfo";
			this.radioTabInfo.DrawIndicator = false;
			this.radioTabInfo.UseUnderline = true;
			this.radioTabInfo.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox1.Add(this.radioTabInfo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabInfo]));
			w6.Position = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabLogistic = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Логистика"));
			this.radioTabLogistic.CanFocus = true;
			this.radioTabLogistic.Name = "radioTabLogistic";
			this.radioTabLogistic.DrawIndicator = false;
			this.radioTabLogistic.UseUnderline = true;
			this.radioTabLogistic.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioTabLogistic);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabLogistic]));
			w7.Position = 4;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabAccounting = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Реквизиты"));
			this.radioTabAccounting.CanFocus = true;
			this.radioTabAccounting.Name = "radioTabAccounting";
			this.radioTabAccounting.DrawIndicator = false;
			this.radioTabAccounting.UseUnderline = true;
			this.radioTabAccounting.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioTabAccounting);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabAccounting]));
			w8.Position = 5;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabFiles = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Файлы"));
			this.radioTabFiles.CanFocus = true;
			this.radioTabFiles.Name = "radioTabFiles";
			this.radioTabFiles.DrawIndicator = false;
			this.radioTabFiles.UseUnderline = true;
			this.radioTabFiles.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioTabFiles);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabFiles]));
			w9.Position = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabContracts = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Договора"));
			this.radioTabContracts.CanFocus = true;
			this.radioTabContracts.Name = "radioTabContracts";
			this.radioTabContracts.DrawIndicator = false;
			this.radioTabContracts.UseUnderline = true;
			this.radioTabContracts.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioTabContracts);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabContracts]));
			w10.Position = 7;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioTabEmployeeDocument = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Документы"));
			this.radioTabEmployeeDocument.CanFocus = true;
			this.radioTabEmployeeDocument.Events = ((global::Gdk.EventMask)(256));
			this.radioTabEmployeeDocument.Name = "radioTabEmployeeDocument";
			this.radioTabEmployeeDocument.DrawIndicator = false;
			this.radioTabEmployeeDocument.UseUnderline = true;
			this.radioTabEmployeeDocument.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioTabEmployeeDocument);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioTabEmployeeDocument]));
			w11.Position = 8;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radioWageParameters = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Зарплата"));
			this.radioWageParameters.CanFocus = true;
			this.radioWageParameters.Events = ((global::Gdk.EventMask)(256));
			this.radioWageParameters.Name = "radioWageParameters";
			this.radioWageParameters.DrawIndicator = false;
			this.radioWageParameters.UseUnderline = true;
			this.radioWageParameters.Group = this.radioTabInfo.Group;
			this.hbox1.Add(this.radioWageParameters);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radioWageParameters]));
			w12.Position = 9;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebookMain = new global::Gtk.Notebook();
			this.notebookMain.CanFocus = true;
			this.notebookMain.Name = "notebookMain";
			this.notebookMain.CurrentPage = 0;
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w14 = new global::Gtk.Viewport();
			w14.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.datatableMain = new global::Gtk.Table(((uint)(18)), ((uint)(3)), false);
			this.datatableMain.Name = "datatableMain";
			this.datatableMain.RowSpacing = ((uint)(6));
			this.datatableMain.ColumnSpacing = ((uint)(6));
			this.datatableMain.BorderWidth = ((uint)(6));
			// Container child datatableMain.Gtk.Table+TableChild
			this.checkbuttonRussianCitizen = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkbuttonRussianCitizen.CanFocus = true;
			this.checkbuttonRussianCitizen.Name = "checkbuttonRussianCitizen";
			this.checkbuttonRussianCitizen.Label = "";
			this.checkbuttonRussianCitizen.DrawIndicator = true;
			this.checkbuttonRussianCitizen.UseUnderline = true;
			this.checkbuttonRussianCitizen.FocusOnClick = false;
			this.checkbuttonRussianCitizen.Relief = ((global::Gtk.ReliefStyle)(2));
			this.datatableMain.Add(this.checkbuttonRussianCitizen);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.checkbuttonRussianCitizen]));
			w15.TopAttach = ((uint)(11));
			w15.BottomAttach = ((uint)(12));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.comboCategory = new global::Gamma.Widgets.yEnumComboBox();
			this.comboCategory.Name = "comboCategory";
			this.comboCategory.ShowSpecialStateAll = false;
			this.comboCategory.ShowSpecialStateNot = false;
			this.comboCategory.UseShortTitle = false;
			this.comboCategory.DefaultFirst = true;
			this.datatableMain.Add(this.comboCategory);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.comboCategory]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.dataentryLastName = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryLastName.CanFocus = true;
			this.dataentryLastName.Name = "dataentryLastName";
			this.dataentryLastName.IsEditable = true;
			this.dataentryLastName.InvisibleChar = '●';
			this.datatableMain.Add(this.dataentryLastName);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.dataentryLastName]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.dataentryName = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryName.CanFocus = true;
			this.dataentryName.Name = "dataentryName";
			this.dataentryName.IsEditable = true;
			this.dataentryName.MaxLength = 100;
			this.dataentryName.InvisibleChar = '●';
			this.datatableMain.Add(this.dataentryName);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.dataentryName]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.dataentryPatronymic = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryPatronymic.CanFocus = true;
			this.dataentryPatronymic.Name = "dataentryPatronymic";
			this.dataentryPatronymic.IsEditable = true;
			this.dataentryPatronymic.InvisibleChar = '●';
			this.datatableMain.Add(this.dataentryPatronymic);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.dataentryPatronymic]));
			w20.TopAttach = ((uint)(3));
			w20.BottomAttach = ((uint)(4));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.datahbox3 = new global::Gtk.HBox();
			this.datahbox3.Name = "datahbox3";
			this.datahbox3.Spacing = 6;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Первый рабочий день:");
			this.datahbox3.Add(this.label16);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.label16]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.ydateFirstWorkDay = new global::QS.Widgets.GtkUI.DatePicker();
			this.ydateFirstWorkDay.Events = ((global::Gdk.EventMask)(256));
			this.ydateFirstWorkDay.Name = "ydateFirstWorkDay";
			this.ydateFirstWorkDay.WithTime = false;
			this.ydateFirstWorkDay.HideCalendarButton = false;
			this.ydateFirstWorkDay.Date = new global::System.DateTime(0);
			this.ydateFirstWorkDay.IsEditable = true;
			this.ydateFirstWorkDay.AutoSeparation = false;
			this.datahbox3.Add(this.ydateFirstWorkDay);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.ydateFirstWorkDay]));
			w22.Position = 1;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.ylabel2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel2.Name = "ylabel2";
			this.ylabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Дата приёма:");
			this.datahbox3.Add(this.ylabel2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.ylabel2]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.dateHired = new global::QS.Widgets.GtkUI.DatePicker();
			this.dateHired.Events = ((global::Gdk.EventMask)(256));
			this.dateHired.Name = "dateHired";
			this.dateHired.WithTime = false;
			this.dateHired.HideCalendarButton = false;
			this.dateHired.Date = new global::System.DateTime(0);
			this.dateHired.IsEditable = true;
			this.dateHired.AutoSeparation = false;
			this.datahbox3.Add(this.dateHired);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.dateHired]));
			w24.Position = 3;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.ylabel3 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel3.Name = "ylabel3";
			this.ylabel3.LabelProp = global::Mono.Unix.Catalog.GetString("Дата увольнения:");
			this.datahbox3.Add(this.ylabel3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.ylabel3]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.dateFired = new global::QS.Widgets.GtkUI.DatePicker();
			this.dateFired.Events = ((global::Gdk.EventMask)(256));
			this.dateFired.Name = "dateFired";
			this.dateFired.WithTime = false;
			this.dateFired.HideCalendarButton = false;
			this.dateFired.Date = new global::System.DateTime(0);
			this.dateFired.IsEditable = true;
			this.dateFired.AutoSeparation = false;
			this.datahbox3.Add(this.dateFired);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.dateFired]));
			w26.Position = 5;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.ylabel4 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel4.Name = "ylabel4";
			this.ylabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Дата расчёта:");
			this.datahbox3.Add(this.ylabel4);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.ylabel4]));
			w27.Position = 6;
			w27.Expand = false;
			w27.Fill = false;
			// Container child datahbox3.Gtk.Box+BoxChild
			this.dateCalculated = new global::QS.Widgets.GtkUI.DatePicker();
			this.dateCalculated.Events = ((global::Gdk.EventMask)(256));
			this.dateCalculated.Name = "dateCalculated";
			this.dateCalculated.WithTime = false;
			this.dateCalculated.HideCalendarButton = false;
			this.dateCalculated.Date = new global::System.DateTime(0);
			this.dateCalculated.IsEditable = true;
			this.dateCalculated.AutoSeparation = false;
			this.datahbox3.Add(this.dateCalculated);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.datahbox3[this.dateCalculated]));
			w28.Position = 7;
			this.datatableMain.Add(this.datahbox3);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.datahbox3]));
			w29.TopAttach = ((uint)(17));
			w29.BottomAttach = ((uint)(18));
			w29.RightAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.entryAddressCurrent = new global::Gamma.GtkWidgets.yEntry();
			this.entryAddressCurrent.CanFocus = true;
			this.entryAddressCurrent.Name = "entryAddressCurrent";
			this.entryAddressCurrent.IsEditable = true;
			this.entryAddressCurrent.InvisibleChar = '●';
			this.datatableMain.Add(this.entryAddressCurrent);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.entryAddressCurrent]));
			w30.TopAttach = ((uint)(16));
			w30.BottomAttach = ((uint)(17));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(3));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.entryAddressRegistration = new global::Gamma.GtkWidgets.yEntry();
			this.entryAddressRegistration.CanFocus = true;
			this.entryAddressRegistration.Name = "entryAddressRegistration";
			this.entryAddressRegistration.IsEditable = true;
			this.entryAddressRegistration.InvisibleChar = '●';
			this.datatableMain.Add(this.entryAddressRegistration);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.entryAddressRegistration]));
			w31.TopAttach = ((uint)(15));
			w31.BottomAttach = ((uint)(16));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.ylblUserLogin = new global::Gamma.GtkWidgets.yLabel();
			this.ylblUserLogin.Name = "ylblUserLogin";
			this.ylblUserLogin.LabelProp = global::Mono.Unix.Catalog.GetString("Логин нового пользователя: ");
			this.hbox14.Add(this.ylblUserLogin);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.ylblUserLogin]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.yentryUserLogin = new global::Gamma.Widgets.yValidatedEntry();
			this.yentryUserLogin.CanFocus = true;
			this.yentryUserLogin.Name = "yentryUserLogin";
			this.yentryUserLogin.IsEditable = true;
			this.yentryUserLogin.InvisibleChar = '•';
			this.hbox14.Add(this.yentryUserLogin);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.yentryUserLogin]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.datatableMain.Add(this.hbox14);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.hbox14]));
			w34.TopAttach = ((uint)(8));
			w34.BottomAttach = ((uint)(9));
			w34.LeftAttach = ((uint)(2));
			w34.RightAttach = ((uint)(3));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.hboxDriversParameters = new global::Gtk.HBox();
			this.hboxDriversParameters.Name = "hboxDriversParameters";
			this.hboxDriversParameters.Spacing = 6;
			// Container child hboxDriversParameters.Gtk.Box+BoxChild
			this.cmbDriverOf = new global::Gamma.Widgets.yEnumComboBox();
			this.cmbDriverOf.Name = "cmbDriverOf";
			this.cmbDriverOf.ShowSpecialStateAll = false;
			this.cmbDriverOf.ShowSpecialStateNot = true;
			this.cmbDriverOf.UseShortTitle = false;
			this.cmbDriverOf.DefaultFirst = false;
			this.hboxDriversParameters.Add(this.cmbDriverOf);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hboxDriversParameters[this.cmbDriverOf]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hboxDriversParameters.Gtk.Box+BoxChild
			this.checkVisitingMaster = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkVisitingMaster.CanFocus = true;
			this.checkVisitingMaster.Name = "checkVisitingMaster";
			this.checkVisitingMaster.Label = global::Mono.Unix.Catalog.GetString("Выездной мастер");
			this.checkVisitingMaster.DrawIndicator = true;
			this.checkVisitingMaster.UseUnderline = true;
			this.hboxDriversParameters.Add(this.checkVisitingMaster);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hboxDriversParameters[this.checkVisitingMaster]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hboxDriversParameters.Gtk.Box+BoxChild
			this.chkDriverForOneDay = new global::Gamma.GtkWidgets.yCheckButton();
			this.chkDriverForOneDay.CanFocus = true;
			this.chkDriverForOneDay.Name = "chkDriverForOneDay";
			this.chkDriverForOneDay.Label = global::Mono.Unix.Catalog.GetString("Разовый водитель");
			this.chkDriverForOneDay.DrawIndicator = true;
			this.chkDriverForOneDay.UseUnderline = true;
			this.hboxDriversParameters.Add(this.chkDriverForOneDay);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hboxDriversParameters[this.chkDriverForOneDay]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hboxDriversParameters.Gtk.Box+BoxChild
			this.checkChainStoreDriver = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkChainStoreDriver.CanFocus = true;
			this.checkChainStoreDriver.Name = "checkChainStoreDriver";
			this.checkChainStoreDriver.Label = global::Mono.Unix.Catalog.GetString("Водитель для сетей");
			this.checkChainStoreDriver.DrawIndicator = true;
			this.checkChainStoreDriver.UseUnderline = true;
			this.hboxDriversParameters.Add(this.checkChainStoreDriver);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hboxDriversParameters[this.checkChainStoreDriver]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			this.datatableMain.Add(this.hboxDriversParameters);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.hboxDriversParameters]));
			w39.TopAttach = ((uint)(5));
			w39.BottomAttach = ((uint)(6));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.hboxSubdivision = new global::Gtk.HBox();
			this.hboxSubdivision.Name = "hboxSubdivision";
			this.hboxSubdivision.Spacing = 6;
			this.datatableMain.Add(this.hboxSubdivision);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.hboxSubdivision]));
			w40.TopAttach = ((uint)(7));
			w40.BottomAttach = ((uint)(8));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Телефон:");
			this.datatableMain.Add(this.label10);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label10]));
			w41.TopAttach = ((uint)(14));
			w41.BottomAttach = ((uint)(15));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Гражданство РФ");
			this.datatableMain.Add(this.label13);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label13]));
			w42.TopAttach = ((uint)(11));
			w42.BottomAttach = ((uint)(12));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Адрес регистрации:");
			this.datatableMain.Add(this.label14);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label14]));
			w43.TopAttach = ((uint)(15));
			w43.BottomAttach = ((uint)(16));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Фактический адрес:");
			this.datatableMain.Add(this.label15);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label15]));
			w44.TopAttach = ((uint)(16));
			w44.BottomAttach = ((uint)(17));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Подразделение:");
			this.datatableMain.Add(this.label18);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label18]));
			w45.TopAttach = ((uint)(7));
			w45.BottomAttach = ((uint)(8));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Фамилия:");
			this.label2.UseMarkup = true;
			this.datatableMain.Add(this.label2);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label2]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.Label20_InnerPhone = new global::Gtk.Label();
			this.Label20_InnerPhone.Name = "Label20_InnerPhone";
			this.Label20_InnerPhone.LabelProp = global::Mono.Unix.Catalog.GetString("Внутренний номер");
			this.datatableMain.Add(this.Label20_InnerPhone);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.Label20_InnerPhone]));
			w47.TopAttach = ((uint)(9));
			w47.BottomAttach = ((uint)(10));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Категория:");
			this.datatableMain.Add(this.label3);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label3]));
			w48.TopAttach = ((uint)(4));
			w48.BottomAttach = ((uint)(5));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Дата рождения:");
			this.datatableMain.Add(this.label4);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label4]));
			w49.TopAttach = ((uint)(10));
			w49.BottomAttach = ((uint)(11));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Имя:");
			this.datatableMain.Add(this.label5);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label5]));
			w50.TopAttach = ((uint)(2));
			w50.BottomAttach = ((uint)(3));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Отчество:");
			this.datatableMain.Add(this.label6);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label6]));
			w51.TopAttach = ((uint)(3));
			w51.BottomAttach = ((uint)(4));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Национальность:");
			this.datatableMain.Add(this.label7);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label7]));
			w52.TopAttach = ((uint)(6));
			w52.BottomAttach = ((uint)(7));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Пользователь:");
			this.datatableMain.Add(this.label8);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label8]));
			w53.TopAttach = ((uint)(8));
			w53.BottomAttach = ((uint)(9));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Оформление:");
			this.datatableMain.Add(this.label9);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.label9]));
			w54.TopAttach = ((uint)(13));
			w54.BottomAttach = ((uint)(14));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.labelCitizenship = new global::Gtk.Label();
			this.labelCitizenship.Name = "labelCitizenship";
			this.labelCitizenship.Xalign = 1F;
			this.labelCitizenship.LabelProp = global::Mono.Unix.Catalog.GetString("Ин.гражданство:");
			this.datatableMain.Add(this.labelCitizenship);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.labelCitizenship]));
			w55.TopAttach = ((uint)(12));
			w55.BottomAttach = ((uint)(13));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.lblDriverOf = new global::Gtk.Label();
			this.lblDriverOf.Name = "lblDriverOf";
			this.lblDriverOf.Xalign = 1F;
			this.lblDriverOf.LabelProp = global::Mono.Unix.Catalog.GetString("Управляет а\\м:");
			this.datatableMain.Add(this.lblDriverOf);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.lblDriverOf]));
			w56.TopAttach = ((uint)(5));
			w56.BottomAttach = ((uint)(6));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.phonesView = new global::Vodovoz.Views.Contacts.PhonesView();
			this.phonesView.Events = ((global::Gdk.EventMask)(256));
			this.phonesView.Name = "phonesView";
			this.phonesView.IsReadOnly = false;
			this.datatableMain.Add(this.phonesView);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.phonesView]));
			w57.TopAttach = ((uint)(14));
			w57.BottomAttach = ((uint)(15));
			w57.LeftAttach = ((uint)(1));
			w57.RightAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.photoviewEmployee = new global::QS.Widgets.GtkUI.PhotoView();
			this.photoviewEmployee.HeightRequest = 250;
			this.photoviewEmployee.Events = ((global::Gdk.EventMask)(256));
			this.photoviewEmployee.Name = "photoviewEmployee";
			this.photoviewEmployee.CanPrint = false;
			this.datatableMain.Add(this.photoviewEmployee);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.photoviewEmployee]));
			w58.BottomAttach = ((uint)(8));
			w58.LeftAttach = ((uint)(2));
			w58.RightAttach = ((uint)(3));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.referenceCitizenship = new global::Gamma.Widgets.yEntryReference();
			this.referenceCitizenship.Events = ((global::Gdk.EventMask)(256));
			this.referenceCitizenship.Name = "referenceCitizenship";
			this.datatableMain.Add(this.referenceCitizenship);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.referenceCitizenship]));
			w59.TopAttach = ((uint)(12));
			w59.BottomAttach = ((uint)(13));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.referenceNationality = new global::Gamma.Widgets.yEntryReference();
			this.referenceNationality.Events = ((global::Gdk.EventMask)(256));
			this.referenceNationality.Name = "referenceNationality";
			this.datatableMain.Add(this.referenceNationality);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.referenceNationality]));
			w60.TopAttach = ((uint)(6));
			w60.BottomAttach = ((uint)(7));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.referenceUser = new global::Gamma.Widgets.yEntryReference();
			this.referenceUser.Events = ((global::Gdk.EventMask)(256));
			this.referenceUser.Name = "referenceUser";
			this.datatableMain.Add(this.referenceUser);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.referenceUser]));
			w61.TopAttach = ((uint)(8));
			w61.BottomAttach = ((uint)(9));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.ydatepicker1 = new global::QS.Widgets.GtkUI.DatePicker();
			this.ydatepicker1.Events = ((global::Gdk.EventMask)(256));
			this.ydatepicker1.Name = "ydatepicker1";
			this.ydatepicker1.WithTime = false;
			this.ydatepicker1.HideCalendarButton = false;
			this.ydatepicker1.Date = new global::System.DateTime(0);
			this.ydatepicker1.IsEditable = true;
			this.ydatepicker1.AutoSeparation = false;
			this.datatableMain.Add(this.ydatepicker1);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.ydatepicker1]));
			w62.TopAttach = ((uint)(10));
			w62.BottomAttach = ((uint)(11));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.yenumcombobox13 = new global::Gamma.Widgets.yEnumComboBox();
			this.yenumcombobox13.Name = "yenumcombobox13";
			this.yenumcombobox13.ShowSpecialStateAll = false;
			this.yenumcombobox13.ShowSpecialStateNot = false;
			this.yenumcombobox13.UseShortTitle = false;
			this.yenumcombobox13.DefaultFirst = false;
			this.datatableMain.Add(this.yenumcombobox13);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.yenumcombobox13]));
			w63.TopAttach = ((uint)(13));
			w63.BottomAttach = ((uint)(14));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.yenumcomboStatus = new global::Gamma.Widgets.yEnumComboBox();
			this.yenumcomboStatus.Name = "yenumcomboStatus";
			this.yenumcomboStatus.ShowSpecialStateAll = false;
			this.yenumcomboStatus.ShowSpecialStateNot = false;
			this.yenumcomboStatus.UseShortTitle = false;
			this.yenumcomboStatus.DefaultFirst = false;
			this.datatableMain.Add(this.yenumcomboStatus);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.yenumcomboStatus]));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatableMain.Gtk.Table+TableChild
			this.ylabel5 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel5.Name = "ylabel5";
			this.ylabel5.Xalign = 1F;
			this.ylabel5.LabelProp = global::Mono.Unix.Catalog.GetString("Статус:");
			this.datatableMain.Add(this.ylabel5);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.datatableMain[this.ylabel5]));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			w14.Add(this.datatableMain);
			this.GtkScrolledWindow.Add(w14);
			this.notebookMain.Add(this.GtkScrolledWindow);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Информация");
			this.notebookMain.SetTabLabel(this.GtkScrolledWindow, this.label1);
			this.label1.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.vboxPageLogistic = new global::Gtk.VBox();
			this.vboxPageLogistic.Name = "vboxPageLogistic";
			this.vboxPageLogistic.Spacing = 6;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboDriverType = new global::Gamma.Widgets.yEnumComboBox();
			this.comboDriverType.Name = "comboDriverType";
			this.comboDriverType.ShowSpecialStateAll = false;
			this.comboDriverType.ShowSpecialStateNot = true;
			this.comboDriverType.UseShortTitle = false;
			this.comboDriverType.DefaultFirst = false;
			this.table1.Add(this.comboDriverType);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table1[this.comboDriverType]));
			w69.TopAttach = ((uint)(2));
			w69.BottomAttach = ((uint)(3));
			w69.LeftAttach = ((uint)(3));
			w69.RightAttach = ((uint)(4));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dataentryAndroidLogin = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryAndroidLogin.CanFocus = true;
			this.dataentryAndroidLogin.Name = "dataentryAndroidLogin";
			this.dataentryAndroidLogin.IsEditable = true;
			this.dataentryAndroidLogin.InvisibleChar = '●';
			this.table1.Add(this.dataentryAndroidLogin);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1[this.dataentryAndroidLogin]));
			w70.TopAttach = ((uint)(1));
			w70.BottomAttach = ((uint)(2));
			w70.LeftAttach = ((uint)(1));
			w70.RightAttach = ((uint)(2));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dataentryAndroidPassword = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryAndroidPassword.CanFocus = true;
			this.dataentryAndroidPassword.Name = "dataentryAndroidPassword";
			this.dataentryAndroidPassword.IsEditable = true;
			this.dataentryAndroidPassword.InvisibleChar = '●';
			this.table1.Add(this.dataentryAndroidPassword);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1[this.dataentryAndroidPassword]));
			w71.TopAttach = ((uint)(1));
			w71.BottomAttach = ((uint)(2));
			w71.LeftAttach = ((uint)(3));
			w71.RightAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dataentryDrivingNumber = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryDrivingNumber.TooltipMarkup = "Десять символов серии и номера без пробелов.";
			this.dataentryDrivingNumber.CanFocus = true;
			this.dataentryDrivingNumber.Name = "dataentryDrivingNumber";
			this.dataentryDrivingNumber.IsEditable = true;
			this.dataentryDrivingNumber.MaxLength = 45;
			this.dataentryDrivingNumber.InvisibleChar = '●';
			this.table1.Add(this.dataentryDrivingNumber);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1[this.dataentryDrivingNumber]));
			w72.LeftAttach = ((uint)(1));
			w72.RightAttach = ((uint)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.yspinDriverSpeed = new global::Gamma.GtkWidgets.ySpinButton(1D, 1000D, 1D);
			this.yspinDriverSpeed.CanFocus = true;
			this.yspinDriverSpeed.Name = "yspinDriverSpeed";
			this.yspinDriverSpeed.Adjustment.PageIncrement = 10D;
			this.yspinDriverSpeed.ClimbRate = 1D;
			this.yspinDriverSpeed.Numeric = true;
			this.yspinDriverSpeed.Value = 1D;
			this.yspinDriverSpeed.ValueAsDecimal = 0m;
			this.yspinDriverSpeed.ValueAsInt = 0;
			this.hbox8.Add(this.yspinDriverSpeed);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.yspinDriverSpeed]));
			w73.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("%");
			this.hbox8.Add(this.label23);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label23]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			this.table1.Add(this.hbox8);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox8]));
			w75.TopAttach = ((uint)(4));
			w75.BottomAttach = ((uint)(5));
			w75.LeftAttach = ((uint)(1));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Водительское удостоверение:");
			this.table1.Add(this.label11);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table1[this.label11]));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 1F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Принадлежность водителя:");
			this.table1.Add(this.label21);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1[this.label21]));
			w77.TopAttach = ((uint)(2));
			w77.BottomAttach = ((uint)(3));
			w77.LeftAttach = ((uint)(2));
			w77.RightAttach = ((uint)(3));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость работы водителя:");
			this.table1.Add(this.label22);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table1[this.label22]));
			w78.TopAttach = ((uint)(4));
			w78.BottomAttach = ((uint)(5));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Приоритет в построении маршрутов:");
			this.table1.Add(this.label26);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table1[this.label26]));
			w79.TopAttach = ((uint)(2));
			w79.BottomAttach = ((uint)(3));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.Xalign = 1F;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Адресов от:");
			this.table1.Add(this.label27);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table1[this.label27]));
			w80.TopAttach = ((uint)(3));
			w80.BottomAttach = ((uint)(4));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.Xalign = 1F;
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("до:");
			this.table1.Add(this.label28);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table1[this.label28]));
			w81.TopAttach = ((uint)(3));
			w81.BottomAttach = ((uint)(4));
			w81.LeftAttach = ((uint)(2));
			w81.RightAttach = ((uint)(3));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAndroid = new global::Gtk.Label();
			this.labelAndroid.Name = "labelAndroid";
			this.labelAndroid.Xalign = 1F;
			this.labelAndroid.LabelProp = global::Mono.Unix.Catalog.GetString("Android логин:");
			this.table1.Add(this.labelAndroid);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table1[this.labelAndroid]));
			w82.TopAttach = ((uint)(1));
			w82.BottomAttach = ((uint)(2));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAndroidPassword = new global::Gtk.Label();
			this.labelAndroidPassword.Name = "labelAndroidPassword";
			this.labelAndroidPassword.Xalign = 1F;
			this.labelAndroidPassword.LabelProp = global::Mono.Unix.Catalog.GetString("пароль:");
			this.table1.Add(this.labelAndroidPassword);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table1[this.labelAndroidPassword]));
			w83.TopAttach = ((uint)(1));
			w83.BottomAttach = ((uint)(2));
			w83.LeftAttach = ((uint)(2));
			w83.RightAttach = ((uint)(3));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.maxAddressesSpin = new global::Gamma.GtkWidgets.ySpinButton(0D, 100D, 1D);
			this.maxAddressesSpin.CanFocus = true;
			this.maxAddressesSpin.Name = "maxAddressesSpin";
			this.maxAddressesSpin.Adjustment.PageIncrement = 10D;
			this.maxAddressesSpin.ClimbRate = 1D;
			this.maxAddressesSpin.Numeric = true;
			this.maxAddressesSpin.ValueAsDecimal = 0m;
			this.maxAddressesSpin.ValueAsInt = 0;
			this.table1.Add(this.maxAddressesSpin);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table1[this.maxAddressesSpin]));
			w84.TopAttach = ((uint)(3));
			w84.BottomAttach = ((uint)(4));
			w84.LeftAttach = ((uint)(3));
			w84.RightAttach = ((uint)(4));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.minAddressesSpin = new global::Gamma.GtkWidgets.ySpinButton(0D, 100D, 1D);
			this.minAddressesSpin.CanFocus = true;
			this.minAddressesSpin.Name = "minAddressesSpin";
			this.minAddressesSpin.Adjustment.PageIncrement = 10D;
			this.minAddressesSpin.ClimbRate = 1D;
			this.minAddressesSpin.Numeric = true;
			this.minAddressesSpin.ValueAsDecimal = 0m;
			this.minAddressesSpin.ValueAsInt = 0;
			this.table1.Add(this.minAddressesSpin);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table1[this.minAddressesSpin]));
			w85.TopAttach = ((uint)(3));
			w85.BottomAttach = ((uint)(4));
			w85.LeftAttach = ((uint)(1));
			w85.RightAttach = ((uint)(2));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.repEntDefaultForwarder = new global::QS.Widgets.GtkUI.RepresentationEntry();
			this.repEntDefaultForwarder.Events = ((global::Gdk.EventMask)(256));
			this.repEntDefaultForwarder.Name = "repEntDefaultForwarder";
			this.table1.Add(this.repEntDefaultForwarder);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table1[this.repEntDefaultForwarder]));
			w86.TopAttach = ((uint)(4));
			w86.BottomAttach = ((uint)(5));
			w86.LeftAttach = ((uint)(3));
			w86.RightAttach = ((uint)(4));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 1F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Экспедитор по умолчанию:");
			this.table1.Add(this.ylabel1);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabel1]));
			w87.TopAttach = ((uint)(4));
			w87.BottomAttach = ((uint)(5));
			w87.LeftAttach = ((uint)(2));
			w87.RightAttach = ((uint)(3));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.yspinTripsPriority = new global::Gamma.GtkWidgets.ySpinButton(1D, 10D, 1D);
			this.yspinTripsPriority.TooltipMarkup = "1 - максимальный приоритет\n10 - минимальный приоритет";
			this.yspinTripsPriority.CanFocus = true;
			this.yspinTripsPriority.Name = "yspinTripsPriority";
			this.yspinTripsPriority.Adjustment.PageIncrement = 1D;
			this.yspinTripsPriority.ClimbRate = 1D;
			this.yspinTripsPriority.Numeric = true;
			this.yspinTripsPriority.Value = 1D;
			this.yspinTripsPriority.ValueAsDecimal = 0m;
			this.yspinTripsPriority.ValueAsInt = 0;
			this.table1.Add(this.yspinTripsPriority);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table1[this.yspinTripsPriority]));
			w88.TopAttach = ((uint)(2));
			w88.BottomAttach = ((uint)(3));
			w88.LeftAttach = ((uint)(1));
			w88.RightAttach = ((uint)(2));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxPageLogistic.Add(this.table1);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.table1]));
			w89.Position = 0;
			w89.Expand = false;
			w89.Fill = false;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 0F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("<b>График работы</b>");
			this.label29.UseMarkup = true;
			this.vboxPageLogistic.Add(this.label29);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.label29]));
			w90.Position = 1;
			w90.Expand = false;
			w90.Fill = false;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.ytreeviewDriverSchedule = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewDriverSchedule.CanFocus = true;
			this.ytreeviewDriverSchedule.Name = "ytreeviewDriverSchedule";
			this.GtkScrolledWindow6.Add(this.ytreeviewDriverSchedule);
			this.vboxPageLogistic.Add(this.GtkScrolledWindow6);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.GtkScrolledWindow6]));
			w92.Position = 2;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.Xalign = 0F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Приоритеты районов доставки</b>");
			this.label25.UseMarkup = true;
			this.vboxPageLogistic.Add(this.label25);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.label25]));
			w93.Position = 3;
			w93.Expand = false;
			w93.Fill = false;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.ytreeviewDistricts = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewDistricts.CanFocus = true;
			this.ytreeviewDistricts.Name = "ytreeviewDistricts";
			this.GtkScrolledWindow2.Add(this.ytreeviewDistricts);
			this.vboxPageLogistic.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.GtkScrolledWindow2]));
			w95.Position = 4;
			// Container child vboxPageLogistic.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.buttonAddDistrict = new global::Gtk.Button();
			this.buttonAddDistrict.CanFocus = true;
			this.buttonAddDistrict.Name = "buttonAddDistrict";
			this.buttonAddDistrict.UseUnderline = true;
			this.buttonAddDistrict.Label = global::Mono.Unix.Catalog.GetString("Добавить район");
			global::Gtk.Image w96 = new global::Gtk.Image();
			w96.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddDistrict.Image = w96;
			this.hbox9.Add(this.buttonAddDistrict);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.buttonAddDistrict]));
			w97.Position = 0;
			w97.Expand = false;
			w97.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.buttonRemoveDistrict = new global::Gtk.Button();
			this.buttonRemoveDistrict.CanFocus = true;
			this.buttonRemoveDistrict.Name = "buttonRemoveDistrict";
			this.buttonRemoveDistrict.UseUnderline = true;
			this.buttonRemoveDistrict.Label = global::Mono.Unix.Catalog.GetString("Убрать район");
			global::Gtk.Image w98 = new global::Gtk.Image();
			w98.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonRemoveDistrict.Image = w98;
			this.hbox9.Add(this.buttonRemoveDistrict);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.buttonRemoveDistrict]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			this.vboxPageLogistic.Add(this.hbox9);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vboxPageLogistic[this.hbox9]));
			w100.Position = 5;
			w100.Expand = false;
			w100.Fill = false;
			this.notebookMain.Add(this.vboxPageLogistic);
			global::Gtk.Notebook.NotebookChild w101 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.vboxPageLogistic]));
			w101.Position = 1;
			// Notebook tab
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Логистика");
			this.notebookMain.SetTabLabel(this.vboxPageLogistic, this.label12);
			this.label12.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("ИНН:");
			this.hbox10.Add(this.label19);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label19]));
			w102.Position = 0;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryInn = new global::Gamma.GtkWidgets.yEntry();
			this.entryInn.CanFocus = true;
			this.entryInn.Name = "entryInn";
			this.entryInn.IsEditable = true;
			this.entryInn.InvisibleChar = '●';
			this.hbox10.Add(this.entryInn);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entryInn]));
			w103.Position = 1;
			this.vbox5.Add(this.hbox10);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.accountsView = new global::QSBanks.AccountsView();
			this.accountsView.Events = ((global::Gdk.EventMask)(256));
			this.accountsView.Name = "accountsView";
			this.accountsView.CanEdit = false;
			this.vbox5.Add(this.accountsView);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.accountsView]));
			w105.Position = 1;
			this.notebookMain.Add(this.vbox5);
			global::Gtk.Notebook.NotebookChild w106 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.vbox5]));
			w106.Position = 2;
			// Notebook tab
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Реквизиты");
			this.notebookMain.SetTabLabel(this.vbox5, this.label17);
			this.label17.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.attachmentFiles = new global::QSAttachment.Attachment();
			this.attachmentFiles.Events = ((global::Gdk.EventMask)(256));
			this.attachmentFiles.Name = "attachmentFiles";
			this.notebookMain.Add(this.attachmentFiles);
			global::Gtk.Notebook.NotebookChild w107 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.attachmentFiles]));
			w107.Position = 3;
			// Notebook tab
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Файлы");
			this.notebookMain.SetTabLabel(this.attachmentFiles, this.label24);
			this.label24.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button53 = new global::Gtk.Button();
			this.button53.CanFocus = true;
			this.button53.Name = "button53";
			this.button53.UseUnderline = true;
			this.button53.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w108 = new global::Gtk.Image();
			w108.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.button53.Image = w108;
			this.hbox13.Add(this.button53);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button53]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.buttonContractEdit = new global::Gtk.Button();
			this.buttonContractEdit.CanFocus = true;
			this.buttonContractEdit.Name = "buttonContractEdit";
			this.buttonContractEdit.UseUnderline = true;
			this.buttonContractEdit.Label = global::Mono.Unix.Catalog.GetString("Изменить");
			global::Gtk.Image w110 = new global::Gtk.Image();
			w110.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonContractEdit.Image = w110;
			this.hbox13.Add(this.buttonContractEdit);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.buttonContractEdit]));
			w111.Position = 1;
			w111.Expand = false;
			w111.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button55 = new global::Gtk.Button();
			this.button55.CanFocus = true;
			this.button55.Name = "button55";
			this.button55.UseUnderline = true;
			this.button55.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			global::Gtk.Image w112 = new global::Gtk.Image();
			w112.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.button55.Image = w112;
			this.hbox13.Add(this.button55);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button55]));
			w113.Position = 2;
			w113.Expand = false;
			w113.Fill = false;
			this.vbox7.Add(this.hbox13);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox13]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.ytreeviewEmployeeContract = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewEmployeeContract.CanFocus = true;
			this.ytreeviewEmployeeContract.Name = "ytreeviewEmployeeContract";
			this.GtkScrolledWindow5.Add(this.ytreeviewEmployeeContract);
			this.vbox7.Add(this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow5]));
			w116.Position = 1;
			this.notebookMain.Add(this.vbox7);
			global::Gtk.Notebook.NotebookChild w117 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.vbox7]));
			w117.Position = 4;
			// Notebook tab
			this.lable66 = new global::Gtk.Label();
			this.lable66.Name = "lable66";
			this.lable66.LabelProp = global::Mono.Unix.Catalog.GetString("Договора");
			this.notebookMain.SetTabLabel(this.vbox7, this.lable66);
			this.lable66.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonAddDocument = new global::Gtk.Button();
			this.buttonAddDocument.CanFocus = true;
			this.buttonAddDocument.Name = "buttonAddDocument";
			this.buttonAddDocument.UseUnderline = true;
			this.buttonAddDocument.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w118 = new global::Gtk.Image();
			w118.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddDocument.Image = w118;
			this.hbox15.Add(this.buttonAddDocument);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.buttonAddDocument]));
			w119.Position = 0;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonDocumentEdit = new global::Gtk.Button();
			this.buttonDocumentEdit.CanFocus = true;
			this.buttonDocumentEdit.Name = "buttonDocumentEdit";
			this.buttonDocumentEdit.UseUnderline = true;
			this.buttonDocumentEdit.Label = global::Mono.Unix.Catalog.GetString("Изменить");
			global::Gtk.Image w120 = new global::Gtk.Image();
			w120.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonDocumentEdit.Image = w120;
			this.hbox15.Add(this.buttonDocumentEdit);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.buttonDocumentEdit]));
			w121.Position = 1;
			w121.Expand = false;
			w121.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			global::Gtk.Image w122 = new global::Gtk.Image();
			w122.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.button3.Image = w122;
			this.hbox15.Add(this.button3);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.button3]));
			w123.Position = 2;
			w123.Expand = false;
			w123.Fill = false;
			this.vbox8.Add(this.hbox15);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox15]));
			w124.Position = 0;
			w124.Expand = false;
			w124.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.ytreeviewEmployeeDocument = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewEmployeeDocument.CanFocus = true;
			this.ytreeviewEmployeeDocument.Name = "ytreeviewEmployeeDocument";
			this.GtkScrolledWindow4.Add(this.ytreeviewEmployeeDocument);
			this.vbox8.Add(this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow4]));
			w126.Position = 1;
			this.notebookMain.Add(this.vbox8);
			global::Gtk.Notebook.NotebookChild w127 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.vbox8]));
			w127.Position = 5;
			// Notebook tab
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Документы");
			this.notebookMain.SetTabLabel(this.vbox8, this.label30);
			this.label30.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.wageParametersView = new global::Vodovoz.Views.WageCalculation.EmployeeWageParametersView();
			this.wageParametersView.Events = ((global::Gdk.EventMask)(256));
			this.wageParametersView.Name = "wageParametersView";
			this.notebookMain.Add(this.wageParametersView);
			global::Gtk.Notebook.NotebookChild w128 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.wageParametersView]));
			w128.Position = 6;
			// Notebook tab
			this.labelWageParameters = new global::Gtk.Label();
			this.labelWageParameters.Name = "labelWageParameters";
			this.labelWageParameters.LabelProp = global::Mono.Unix.Catalog.GetString("Зарплата");
			this.notebookMain.SetTabLabel(this.wageParametersView, this.labelWageParameters);
			this.labelWageParameters.ShowAll();
			this.vbox1.Add(this.notebookMain);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebookMain]));
			w129.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.radioTabInfo.Toggled += new global::System.EventHandler(this.OnRadioTabInfoToggled);
			this.radioTabLogistic.Toggled += new global::System.EventHandler(this.OnRadioTabLogisticToggled);
			this.radioTabAccounting.Toggled += new global::System.EventHandler(this.OnRadioTabAccountingToggled);
			this.radioTabFiles.Toggled += new global::System.EventHandler(this.OnRadioTabFilesToggled);
			this.radioTabContracts.Clicked += new global::System.EventHandler(this.OnRadioTabContractsToggled);
			this.radioTabEmployeeDocument.Clicked += new global::System.EventHandler(this.OnRadioTabEmployeeDocumentToggled);
			this.radioWageParameters.Clicked += new global::System.EventHandler(this.OnRadioWageParametersClicked);
			this.comboCategory.EnumItemSelected += new global::System.EventHandler<Gamma.Widgets.ItemSelectedEventArgs>(this.OnComboCategoryEnumItemSelected);
			this.checkbuttonRussianCitizen.Toggled += new global::System.EventHandler(this.OnRussianCitizenToggled);
			this.buttonAddDistrict.Clicked += new global::System.EventHandler(this.OnButtonAddDistrictClicked);
			this.buttonRemoveDistrict.Clicked += new global::System.EventHandler(this.OnButtonRemoveDistrictClicked);
			this.button53.Clicked += new global::System.EventHandler(this.OnAddContractButtonCliked);
			this.buttonContractEdit.Clicked += new global::System.EventHandler(this.OnButtonEditContractClicked);
			this.button55.Clicked += new global::System.EventHandler(this.OnButtonRemoveContractClicked);
			this.ytreeviewEmployeeContract.RowActivated += new global::Gtk.RowActivatedHandler(this.OnEmployeeContractRowActivated);
			this.buttonAddDocument.Clicked += new global::System.EventHandler(this.OnButtonAddDocumentClicked);
			this.buttonDocumentEdit.Clicked += new global::System.EventHandler(this.OnButtonEditDocumentClicked);
			this.button3.Clicked += new global::System.EventHandler(this.OnButtonRemoveDocumentClicked);
			this.ytreeviewEmployeeDocument.RowActivated += new global::Gtk.RowActivatedHandler(this.OnEmployeeDocumentRowActivated);
		}
	}
}
