
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz
{
	public partial class OrderDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.ToggleButton toggleInformation;
		
		private global::Gtk.ToggleButton toggleGoods;
		
		private global::Gtk.ToggleButton toggleEquipment;
		
		private global::Gtk.ToggleButton toggleService;
		
		private global::Gtk.ToggleButton toggleDocuments;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.DataBindings.DataTable datatable1;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumStatus;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.DataBindings.DataEntryReference referenceClient;
		
		private global::Gtk.DataBindings.DataEntryReference referenceDeliveryPoint;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.DataBindings.DataTable datatable2;
		
		private global::Gtk.DataBindings.DataCheckButton checkSelfDelivery;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label labelDeliveryDate;
		
		private global::Gtk.Label labelDeliverySchedule;
		
		private global::QSOrmProject.DataDatePicker pickerDeliveryDate;
		
		private global::Gtk.DataBindings.DataEntryReference referenceDeliverySchedule;
		
		private global::Gtk.HSeparator hseparator6;
		
		private global::Gtk.DataBindings.DataTable datatable3;
		
		private global::Gtk.DataBindings.DataCheckButton checkDelivered;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumSignatureType;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.DataBindings.DataTextView textComments;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.DataBindings.DataEntryReference referencePreviousOrder;
		
		private global::Gtk.DataBindings.DataSpinButton spinBottlesReturn;
		
		private global::Gtk.DataBindings.DataSpinButton spinSumToReceive;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label18;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Vodovoz.OrderDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Vodovoz.OrderDlg";
			// Container child Vodovoz.OrderDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleInformation = new global::Gtk.ToggleButton ();
			this.toggleInformation.CanFocus = true;
			this.toggleInformation.Name = "toggleInformation";
			this.toggleInformation.UseUnderline = true;
			this.toggleInformation.Label = global::Mono.Unix.Catalog.GetString ("Информация");
			this.hbox1.Add (this.toggleInformation);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleInformation]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleGoods = new global::Gtk.ToggleButton ();
			this.toggleGoods.CanFocus = true;
			this.toggleGoods.Name = "toggleGoods";
			this.toggleGoods.UseUnderline = true;
			this.toggleGoods.Label = global::Mono.Unix.Catalog.GetString ("Товары");
			this.hbox1.Add (this.toggleGoods);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleGoods]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleEquipment = new global::Gtk.ToggleButton ();
			this.toggleEquipment.CanFocus = true;
			this.toggleEquipment.Name = "toggleEquipment";
			this.toggleEquipment.UseUnderline = true;
			this.toggleEquipment.Label = global::Mono.Unix.Catalog.GetString ("Оборудование");
			this.hbox1.Add (this.toggleEquipment);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleEquipment]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleService = new global::Gtk.ToggleButton ();
			this.toggleService.CanFocus = true;
			this.toggleService.Name = "toggleService";
			this.toggleService.UseUnderline = true;
			this.toggleService.Label = global::Mono.Unix.Catalog.GetString ("Сервис");
			this.hbox1.Add (this.toggleService);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleService]));
			w9.Position = 6;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleDocuments = new global::Gtk.ToggleButton ();
			this.toggleDocuments.CanFocus = true;
			this.toggleDocuments.Name = "toggleDocuments";
			this.toggleDocuments.UseUnderline = true;
			this.toggleDocuments.Label = global::Mono.Unix.Catalog.GetString ("Документы");
			this.hbox1.Add (this.toggleDocuments);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleDocuments]));
			w10.Position = 7;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(6));
			this.datatable1.ColumnSpacing = ((uint)(6));
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			// Container child datatable1.Gtk.Table+TableChild
			this.enumStatus = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumStatus.Name = "enumStatus";
			this.enumStatus.InheritedBoundaryDataSource = false;
			this.enumStatus.InheritedDataSource = true;
			this.enumStatus.Mappings = "OrderStatus";
			this.enumStatus.InheritedBoundaryDataSource = false;
			this.enumStatus.InheritedDataSource = true;
			this.enumStatus.Mappings = "OrderStatus";
			this.datatable1.Add (this.enumStatus);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumStatus]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Статус:");
			this.datatable1.Add (this.label1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label1]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 160;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Клиент:");
			this.datatable1.Add (this.label2);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label2]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Точка доставки:");
			this.datatable1.Add (this.label3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label3]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceClient = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceClient.Events = ((global::Gdk.EventMask)(256));
			this.referenceClient.Name = "referenceClient";
			this.referenceClient.DisplayFields = new string[] {
				"Name"
			};
			this.referenceClient.DisplayFormatString = "{0}";
			this.referenceClient.InheritedDataSource = true;
			this.referenceClient.Mappings = "Client";
			this.referenceClient.InheritedBoundaryDataSource = false;
			this.referenceClient.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceClient);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceClient]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceDeliveryPoint = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceDeliveryPoint.Events = ((global::Gdk.EventMask)(256));
			this.referenceDeliveryPoint.Name = "referenceDeliveryPoint";
			this.referenceDeliveryPoint.DisplayFields = new string[] {
				"Name"
			};
			this.referenceDeliveryPoint.DisplayFormatString = "{0}";
			this.referenceDeliveryPoint.InheritedDataSource = true;
			this.referenceDeliveryPoint.Mappings = "DeliveryPoint";
			this.referenceDeliveryPoint.InheritedBoundaryDataSource = false;
			this.referenceDeliveryPoint.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceDeliveryPoint);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceDeliveryPoint]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.datatable1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.datatable1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox3.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator5]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.datatable2 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
			this.datatable2.Name = "datatable2";
			this.datatable2.RowSpacing = ((uint)(6));
			this.datatable2.ColumnSpacing = ((uint)(6));
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			// Container child datatable2.Gtk.Table+TableChild
			this.checkSelfDelivery = new global::Gtk.DataBindings.DataCheckButton ();
			this.checkSelfDelivery.CanFocus = true;
			this.checkSelfDelivery.Name = "checkSelfDelivery";
			this.checkSelfDelivery.Label = global::Mono.Unix.Catalog.GetString ("Самовывоз");
			this.checkSelfDelivery.DrawIndicator = true;
			this.checkSelfDelivery.UseUnderline = true;
			this.checkSelfDelivery.InheritedDataSource = true;
			this.checkSelfDelivery.Mappings = "SelfDelivery";
			this.checkSelfDelivery.InheritedBoundaryDataSource = false;
			this.checkSelfDelivery.Editable = false;
			this.checkSelfDelivery.AutomaticTitle = false;
			this.checkSelfDelivery.InheritedBoundaryDataSource = false;
			this.checkSelfDelivery.InheritedDataSource = true;
			this.checkSelfDelivery.Mappings = "SelfDelivery";
			this.datatable2.Add (this.checkSelfDelivery);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.checkSelfDelivery]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.datatable2.Add (this.label16);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label16]));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.labelDeliveryDate = new global::Gtk.Label ();
			this.labelDeliveryDate.WidthRequest = 160;
			this.labelDeliveryDate.Name = "labelDeliveryDate";
			this.labelDeliveryDate.Xalign = 1F;
			this.labelDeliveryDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата доставки:");
			this.datatable2.Add (this.labelDeliveryDate);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.labelDeliveryDate]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.labelDeliverySchedule = new global::Gtk.Label ();
			this.labelDeliverySchedule.Name = "labelDeliverySchedule";
			this.labelDeliverySchedule.Xalign = 1F;
			this.labelDeliverySchedule.LabelProp = global::Mono.Unix.Catalog.GetString ("Время доставки:");
			this.datatable2.Add (this.labelDeliverySchedule);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.labelDeliverySchedule]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.pickerDeliveryDate = new global::QSOrmProject.DataDatePicker ();
			this.pickerDeliveryDate.Events = ((global::Gdk.EventMask)(256));
			this.pickerDeliveryDate.Name = "pickerDeliveryDate";
			this.pickerDeliveryDate.Date = new global::System.DateTime (0);
			this.pickerDeliveryDate.IsEditable = false;
			this.pickerDeliveryDate.AutoSeparation = false;
			this.pickerDeliveryDate.InheritedDataSource = true;
			this.pickerDeliveryDate.Mappings = "DeliveryDate";
			this.pickerDeliveryDate.InheritedBoundaryDataSource = false;
			this.datatable2.Add (this.pickerDeliveryDate);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.pickerDeliveryDate]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.referenceDeliverySchedule = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceDeliverySchedule.Events = ((global::Gdk.EventMask)(256));
			this.referenceDeliverySchedule.Name = "referenceDeliverySchedule";
			this.referenceDeliverySchedule.DisplayFields = new string[] {
				"Name"
			};
			this.referenceDeliverySchedule.DisplayFormatString = "{0}";
			this.referenceDeliverySchedule.InheritedDataSource = true;
			this.referenceDeliverySchedule.Mappings = "DeliverySchedule";
			this.referenceDeliverySchedule.InheritedBoundaryDataSource = false;
			this.referenceDeliverySchedule.CursorPointsEveryType = false;
			this.datatable2.Add (this.referenceDeliverySchedule);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.referenceDeliverySchedule]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.datatable2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.datatable2]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox3.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator6]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.datatable3 = new global::Gtk.DataBindings.DataTable (((uint)(6)), ((uint)(2)), false);
			this.datatable3.Name = "datatable3";
			this.datatable3.RowSpacing = ((uint)(6));
			this.datatable3.ColumnSpacing = ((uint)(6));
			this.datatable3.InheritedDataSource = false;
			this.datatable3.InheritedBoundaryDataSource = false;
			this.datatable3.InheritedDataSource = false;
			this.datatable3.InheritedBoundaryDataSource = false;
			// Container child datatable3.Gtk.Table+TableChild
			this.checkDelivered = new global::Gtk.DataBindings.DataCheckButton ();
			this.checkDelivered.CanFocus = true;
			this.checkDelivered.Name = "checkDelivered";
			this.checkDelivered.Label = global::Mono.Unix.Catalog.GetString ("Доставлен");
			this.checkDelivered.DrawIndicator = true;
			this.checkDelivered.UseUnderline = true;
			this.checkDelivered.InheritedDataSource = true;
			this.checkDelivered.Mappings = "Shipped";
			this.checkDelivered.InheritedBoundaryDataSource = false;
			this.checkDelivered.Editable = false;
			this.checkDelivered.AutomaticTitle = false;
			this.checkDelivered.InheritedBoundaryDataSource = false;
			this.checkDelivered.InheritedDataSource = true;
			this.checkDelivered.Mappings = "Shipped";
			this.datatable3.Add (this.checkDelivered);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.checkDelivered]));
			w28.TopAttach = ((uint)(5));
			w28.BottomAttach = ((uint)(6));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.enumSignatureType = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumSignatureType.Name = "enumSignatureType";
			this.enumSignatureType.InheritedBoundaryDataSource = false;
			this.enumSignatureType.InheritedDataSource = true;
			this.enumSignatureType.Mappings = "SignatureType";
			this.enumSignatureType.InheritedBoundaryDataSource = false;
			this.enumSignatureType.InheritedDataSource = true;
			this.enumSignatureType.Mappings = "SignatureType";
			this.datatable3.Add (this.enumSignatureType);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.enumSignatureType]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textComments = new global::Gtk.DataBindings.DataTextView ();
			this.textComments.CanFocus = true;
			this.textComments.Name = "textComments";
			this.textComments.InheritedDataSource = true;
			this.textComments.Mappings = "Comment";
			this.textComments.InheritedBoundaryDataSource = false;
			this.textComments.InheritedDataSource = true;
			this.textComments.Mappings = "Comment";
			this.textComments.InheritedBoundaryDataSource = false;
			this.GtkScrolledWindow.Add (this.textComments);
			this.datatable3.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.GtkScrolledWindow]));
			w31.TopAttach = ((uint)(3));
			w31.BottomAttach = ((uint)(4));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.datatable3.Add (this.label10);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label10]));
			w32.TopAttach = ((uint)(3));
			w32.BottomAttach = ((uint)(4));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Сумма к получению:");
			this.datatable3.Add (this.label11);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label11]));
			w33.TopAttach = ((uint)(4));
			w33.BottomAttach = ((uint)(5));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.datatable3.Add (this.label12);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label12]));
			w34.TopAttach = ((uint)(5));
			w34.BottomAttach = ((uint)(6));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Бутылей на возврат:");
			this.datatable3.Add (this.label7);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label7]));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.WidthRequest = 160;
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Предыдущий заказ:");
			this.datatable3.Add (this.label8);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label8]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Подписание документов:");
			this.datatable3.Add (this.label9);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.label9]));
			w37.TopAttach = ((uint)(2));
			w37.BottomAttach = ((uint)(3));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.referencePreviousOrder = new global::Gtk.DataBindings.DataEntryReference ();
			this.referencePreviousOrder.Events = ((global::Gdk.EventMask)(256));
			this.referencePreviousOrder.Name = "referencePreviousOrder";
			this.referencePreviousOrder.DisplayFields = new string[] {
				"Id"
			};
			this.referencePreviousOrder.DisplayFormatString = "{0}";
			this.referencePreviousOrder.InheritedDataSource = true;
			this.referencePreviousOrder.Mappings = "PreviousOrder";
			this.referencePreviousOrder.InheritedBoundaryDataSource = false;
			this.referencePreviousOrder.CursorPointsEveryType = false;
			this.datatable3.Add (this.referencePreviousOrder);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.referencePreviousOrder]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.spinBottlesReturn = new global::Gtk.DataBindings.DataSpinButton (0, 1000, 1);
			this.spinBottlesReturn.CanFocus = true;
			this.spinBottlesReturn.Name = "spinBottlesReturn";
			this.spinBottlesReturn.Adjustment.PageIncrement = 10;
			this.spinBottlesReturn.ClimbRate = 1;
			this.spinBottlesReturn.Numeric = true;
			this.spinBottlesReturn.InheritedDataSource = true;
			this.spinBottlesReturn.Mappings = "BottlesReturn";
			this.spinBottlesReturn.InheritedBoundaryDataSource = false;
			this.spinBottlesReturn.InheritedDataSource = true;
			this.spinBottlesReturn.Mappings = "BottlesReturn";
			this.spinBottlesReturn.InheritedBoundaryDataSource = false;
			this.datatable3.Add (this.spinBottlesReturn);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.spinBottlesReturn]));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable3.Gtk.Table+TableChild
			this.spinSumToReceive = new global::Gtk.DataBindings.DataSpinButton (0, 1000000, 1);
			this.spinSumToReceive.Sensitive = false;
			this.spinSumToReceive.CanFocus = true;
			this.spinSumToReceive.Name = "spinSumToReceive";
			this.spinSumToReceive.Adjustment.PageIncrement = 10;
			this.spinSumToReceive.ClimbRate = 1;
			this.spinSumToReceive.Numeric = true;
			this.spinSumToReceive.InheritedDataSource = true;
			this.spinSumToReceive.Mappings = "SumToReceive";
			this.spinSumToReceive.InheritedBoundaryDataSource = false;
			this.spinSumToReceive.InheritedDataSource = true;
			this.spinSumToReceive.Mappings = "SumToReceive";
			this.spinSumToReceive.InheritedBoundaryDataSource = false;
			this.datatable3.Add (this.spinSumToReceive);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.datatable3 [this.spinSumToReceive]));
			w40.TopAttach = ((uint)(4));
			w40.BottomAttach = ((uint)(5));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.datatable3);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.datatable3]));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			this.notebook1.Add (this.vbox3);
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.vbox3, this.label13);
			this.label13.ShowAll ();
			// Notebook tab
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w43.Visible = true;
			this.notebook1.Add (w43);
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Товары");
			this.notebook1.SetTabLabel (w43, this.label14);
			this.label14.ShowAll ();
			// Notebook tab
			global::Gtk.Label w44 = new global::Gtk.Label ();
			w44.Visible = true;
			this.notebook1.Add (w44);
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Оборудование");
			this.notebook1.SetTabLabel (w44, this.label15);
			this.label15.ShowAll ();
			// Notebook tab
			global::Gtk.Label w45 = new global::Gtk.Label ();
			w45.Visible = true;
			this.notebook1.Add (w45);
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Сервис");
			this.notebook1.SetTabLabel (w45, this.label17);
			this.label17.ShowAll ();
			// Notebook tab
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.Visible = true;
			this.notebook1.Add (w46);
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Документы");
			this.notebook1.SetTabLabel (w46, this.label18);
			this.label18.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w47.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.toggleInformation.Toggled += new global::System.EventHandler (this.OnToggleInformationToggled);
			this.toggleGoods.Toggled += new global::System.EventHandler (this.OnToggleGoodsToggled);
			this.toggleEquipment.Toggled += new global::System.EventHandler (this.OnToggleEquipmentToggled);
			this.toggleService.Toggled += new global::System.EventHandler (this.OnToggleServiceToggled);
			this.toggleDocuments.Toggled += new global::System.EventHandler (this.OnToggleDocumentsToggled);
			this.checkSelfDelivery.Toggled += new global::System.EventHandler (this.OnCheckSelfDeliveryToggled);
		}
	}
}
