
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Mango
{
	public partial class IncomingCallView
	{
		private global::Gtk.VBox MainVbox;

		private global::Gtk.HBox hbox2;

		private global::Gamma.GtkWidgets.yButton RollUpButton;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label Label1_Conversation;

		private global::Gamma.GtkWidgets.yLabel CallNumberLabel;

		private global::Gamma.GtkWidgets.yLabel TimerLabel;

		private global::Gtk.HBox hbox3;

		private global::Gamma.GtkWidgets.yButton NewClientButton;

		private global::Gamma.GtkWidgets.yButton ExistingClientButton;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Table table5;

		private global::Gtk.Button ComplaintButton;

		private global::Gtk.Button CostAndDeliveryIntervalButton;

		private global::Gtk.Button StockBalnce;

		private global::Gtk.Table table4;

		private global::Gamma.GtkWidgets.yButton FinishButton;

		private global::Gamma.GtkWidgets.yButton ForwardingButton;

		private global::Gamma.GtkWidgets.yButton RetentionButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Mango.IncomingCallView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Mango.IncomingCallView";
			// Container child Vodovoz.Views.Mango.IncomingCallView.Gtk.Container+ContainerChild
			this.MainVbox = new global::Gtk.VBox();
			this.MainVbox.Name = "MainVbox";
			this.MainVbox.Spacing = 6;
			this.MainVbox.BorderWidth = ((uint)(9));
			// Container child MainVbox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.RollUpButton = new global::Gamma.GtkWidgets.yButton();
			this.RollUpButton.CanFocus = true;
			this.RollUpButton.Name = "RollUpButton";
			this.RollUpButton.UseUnderline = true;
			this.RollUpButton.Label = global::Mono.Unix.Catalog.GetString("-");
			this.hbox2.Add(this.RollUpButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.RollUpButton]));
			w1.Position = 2;
			w1.Expand = false;
			w1.Fill = false;
			this.MainVbox.Add(this.hbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.hbox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Label1_Conversation = new global::Gtk.Label();
			this.Label1_Conversation.Name = "Label1_Conversation";
			this.Label1_Conversation.Xalign = 0F;
			this.Label1_Conversation.LabelProp = global::Mono.Unix.Catalog.GetString("Разговор:");
			this.hbox1.Add(this.Label1_Conversation);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Label1_Conversation]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.CallNumberLabel = new global::Gamma.GtkWidgets.yLabel();
			this.CallNumberLabel.Name = "CallNumberLabel";
			this.CallNumberLabel.Yalign = 0F;
			this.CallNumberLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Телефон");
			this.CallNumberLabel.Justify = ((global::Gtk.Justification)(2));
			this.CallNumberLabel.WidthChars = 0;
			this.CallNumberLabel.MaxWidthChars = 0;
			this.hbox1.Add(this.CallNumberLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.CallNumberLabel]));
			w4.Position = 1;
			w4.Padding = ((uint)(72));
			// Container child hbox1.Gtk.Box+BoxChild
			this.TimerLabel = new global::Gamma.GtkWidgets.yLabel();
			this.TimerLabel.Name = "TimerLabel";
			this.TimerLabel.Xalign = 1F;
			this.TimerLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Timer");
			this.TimerLabel.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add(this.TimerLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.TimerLabel]));
			w5.Position = 2;
			this.MainVbox.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.NewClientButton = new global::Gamma.GtkWidgets.yButton();
			this.NewClientButton.CanFocus = true;
			this.NewClientButton.Name = "NewClientButton";
			this.NewClientButton.UseUnderline = true;
			this.NewClientButton.Label = global::Mono.Unix.Catalog.GetString("Новый клиент");
			this.hbox3.Add(this.NewClientButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.NewClientButton]));
			w7.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ExistingClientButton = new global::Gamma.GtkWidgets.yButton();
			this.ExistingClientButton.CanFocus = true;
			this.ExistingClientButton.Name = "ExistingClientButton";
			this.ExistingClientButton.UseUnderline = true;
			this.ExistingClientButton.Label = global::Mono.Unix.Catalog.GetString("Существующий клиент");
			this.hbox3.Add(this.ExistingClientButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.ExistingClientButton]));
			w8.Position = 1;
			this.MainVbox.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table(((uint)(1)), ((uint)(5)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.ComplaintButton = new global::Gtk.Button();
			this.ComplaintButton.CanFocus = true;
			this.ComplaintButton.Name = "ComplaintButton";
			this.ComplaintButton.UseUnderline = true;
			this.ComplaintButton.Label = global::Mono.Unix.Catalog.GetString("+Жалоба");
			this.table5.Add(this.ComplaintButton);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5[this.ComplaintButton]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.CostAndDeliveryIntervalButton = new global::Gtk.Button();
			this.CostAndDeliveryIntervalButton.CanFocus = true;
			this.CostAndDeliveryIntervalButton.Name = "CostAndDeliveryIntervalButton";
			this.CostAndDeliveryIntervalButton.UseUnderline = true;
			this.CostAndDeliveryIntervalButton.Label = global::Mono.Unix.Catalog.GetString("Стоимость и \n  интервалы\n   доставки");
			this.table5.Add(this.CostAndDeliveryIntervalButton);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.CostAndDeliveryIntervalButton]));
			w11.LeftAttach = ((uint)(4));
			w11.RightAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(1));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.StockBalnce = new global::Gtk.Button();
			this.StockBalnce.CanFocus = true;
			this.StockBalnce.Name = "StockBalnce";
			this.StockBalnce.UseUnderline = true;
			this.StockBalnce.Label = global::Mono.Unix.Catalog.GetString("Складские остатки");
			this.table5.Add(this.StockBalnce);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.StockBalnce]));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add(this.table5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.table5]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table(((uint)(1)), ((uint)(6)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.FinishButton = new global::Gamma.GtkWidgets.yButton();
			this.FinishButton.CanFocus = true;
			this.FinishButton.Name = "FinishButton";
			this.FinishButton.UseUnderline = true;
			this.FinishButton.Label = global::Mono.Unix.Catalog.GetString("Завершить");
			this.table4.Add(this.FinishButton);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.FinishButton]));
			w14.LeftAttach = ((uint)(5));
			w14.RightAttach = ((uint)(6));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.ForwardingButton = new global::Gamma.GtkWidgets.yButton();
			this.ForwardingButton.CanFocus = true;
			this.ForwardingButton.Name = "ForwardingButton";
			this.ForwardingButton.UseUnderline = true;
			this.ForwardingButton.Label = global::Mono.Unix.Catalog.GetString("Переадресация");
			this.table4.Add(this.ForwardingButton);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.ForwardingButton]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.RetentionButton = new global::Gamma.GtkWidgets.yButton();
			this.RetentionButton.CanFocus = true;
			this.RetentionButton.Name = "RetentionButton";
			this.RetentionButton.UseUnderline = true;
			this.RetentionButton.Label = global::Mono.Unix.Catalog.GetString("|| Удержание");
			this.table4.Add(this.RetentionButton);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4[this.RetentionButton]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add(this.table4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.table4]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.MainVbox.Add(this.vbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.vbox6]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.MainVbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.NewClientButton.Clicked += new global::System.EventHandler(this.Clicked_NewClientButton);
			this.ExistingClientButton.Clicked += new global::System.EventHandler(this.Clicked_ExistingClientButton);
			this.StockBalnce.Clicked += new global::System.EventHandler(this.Clicked_StockBalnce);
			this.CostAndDeliveryIntervalButton.Clicked += new global::System.EventHandler(this.Clicked_CostAndDeliveryIntervalButton);
			this.ComplaintButton.Clicked += new global::System.EventHandler(this.Clicked_ComplaintButton);
		}
	}
}
