
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.JournalFilters
{
	public partial class WarehouseFilter
	{
		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yCheckButton ycheckRestrictArchive;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.JournalFilters.WarehouseFilter
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.JournalFilters.WarehouseFilter";
			// Container child Vodovoz.JournalFilters.WarehouseFilter.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ycheckRestrictArchive = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckRestrictArchive.CanFocus = true;
			this.ycheckRestrictArchive.Name = "ycheckRestrictArchive";
			this.ycheckRestrictArchive.Label = global::Mono.Unix.Catalog.GetString("Скрыть архивные");
			this.ycheckRestrictArchive.DrawIndicator = true;
			this.ycheckRestrictArchive.UseUnderline = true;
			this.hbox1.Add(this.ycheckRestrictArchive);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ycheckRestrictArchive]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
