
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz
{
	public partial class OrderDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.RadioButton toggleInformation;
		
		private global::Gtk.RadioButton toggleGoods;
		
		private global::Gtk.RadioButton toggleEquipment;
		
		private global::Gtk.RadioButton toggleService;
		
		private global::Gtk.RadioButton toggleDocuments;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.DataBindings.DataTable datatable1;
		
		private global::Gtk.DataBindings.DataCheckButton checkDelivered;
		
		private global::Gtk.DataBindings.DataCheckButton checkSelfDelivery;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumPaymentType;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumSignatureType;
		
		private global::Gtk.DataBindings.DataEnumComboBox enumStatus;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.DataBindings.DataTextView textComments;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.HSeparator hseparator6;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label labelDeliveryDate;
		
		private global::Gtk.Label labelDeliverySchedule;
		
		private global::Gtk.Label labelPreviousOrder;
		
		private global::QSOrmProject.DataDatePicker pickerDeliveryDate;
		
		private global::Gtk.DataBindings.DataEntryReference referenceClient;
		
		private global::Gtk.DataBindings.DataEntryReference referenceDeliveryPoint;
		
		private global::Gtk.DataBindings.DataEntryReference referenceDeliverySchedule;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.DataBindings.DataTreeView treeItems;
		
		private global::Gtk.DataBindings.DataTable datatable2;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label labelSum;
		
		private global::Gtk.DataBindings.DataSpinButton spinBottlesReturn;
		
		private global::Gtk.DataBindings.DataSpinButton spinSumToReceive;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button buttonAddForSale;
		
		private global::QSOrmProject.EnumMenuButton enumAddRentButton;
		
		private global::Gtk.VSeparator vseparator2;
		
		private global::Gtk.Button buttonDelete;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.DataBindings.DataTreeView treeEquipment;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.DataBindings.DataTreeView treeDocuments;
		
		private global::Gtk.Label label18;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Vodovoz.OrderDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Vodovoz.OrderDlg";
			// Container child Vodovoz.OrderDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleInformation = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Информация"));
			this.toggleInformation.CanFocus = true;
			this.toggleInformation.Name = "toggleInformation";
			this.toggleInformation.DrawIndicator = false;
			this.toggleInformation.UseUnderline = true;
			this.toggleInformation.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox1.Add (this.toggleInformation);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleInformation]));
			w6.Position = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleGoods = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Товары"));
			this.toggleGoods.CanFocus = true;
			this.toggleGoods.Name = "toggleGoods";
			this.toggleGoods.DrawIndicator = false;
			this.toggleGoods.UseUnderline = true;
			this.toggleGoods.Group = this.toggleInformation.Group;
			this.hbox1.Add (this.toggleGoods);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleGoods]));
			w7.Position = 4;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleEquipment = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Оборудование"));
			this.toggleEquipment.CanFocus = true;
			this.toggleEquipment.Name = "toggleEquipment";
			this.toggleEquipment.DrawIndicator = false;
			this.toggleEquipment.UseUnderline = true;
			this.toggleEquipment.Group = this.toggleInformation.Group;
			this.hbox1.Add (this.toggleEquipment);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleEquipment]));
			w8.Position = 5;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleService = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Сервис"));
			this.toggleService.CanFocus = true;
			this.toggleService.Name = "toggleService";
			this.toggleService.DrawIndicator = false;
			this.toggleService.UseUnderline = true;
			this.toggleService.Group = this.toggleInformation.Group;
			this.hbox1.Add (this.toggleService);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleService]));
			w9.Position = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toggleDocuments = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Документы"));
			this.toggleDocuments.CanFocus = true;
			this.toggleDocuments.Name = "toggleDocuments";
			this.toggleDocuments.DrawIndicator = false;
			this.toggleDocuments.UseUnderline = true;
			this.toggleDocuments.Group = this.toggleInformation.Group;
			this.hbox1.Add (this.toggleDocuments);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleDocuments]));
			w10.Position = 7;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(12)), ((uint)(4)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(6));
			this.datatable1.ColumnSpacing = ((uint)(6));
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			// Container child datatable1.Gtk.Table+TableChild
			this.checkDelivered = new global::Gtk.DataBindings.DataCheckButton ();
			this.checkDelivered.CanFocus = true;
			this.checkDelivered.Name = "checkDelivered";
			this.checkDelivered.Label = global::Mono.Unix.Catalog.GetString ("Отгружен по платежке");
			this.checkDelivered.DrawIndicator = true;
			this.checkDelivered.UseUnderline = true;
			this.checkDelivered.InheritedDataSource = true;
			this.checkDelivered.Mappings = "Shipped";
			this.checkDelivered.InheritedBoundaryDataSource = false;
			this.checkDelivered.Editable = true;
			this.checkDelivered.AutomaticTitle = false;
			this.checkDelivered.InheritedBoundaryDataSource = false;
			this.checkDelivered.InheritedDataSource = true;
			this.checkDelivered.Mappings = "Shipped";
			this.datatable1.Add (this.checkDelivered);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.checkDelivered]));
			w12.TopAttach = ((uint)(11));
			w12.BottomAttach = ((uint)(12));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(0));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.checkSelfDelivery = new global::Gtk.DataBindings.DataCheckButton ();
			this.checkSelfDelivery.CanFocus = true;
			this.checkSelfDelivery.Name = "checkSelfDelivery";
			this.checkSelfDelivery.Label = global::Mono.Unix.Catalog.GetString ("Самовывоз");
			this.checkSelfDelivery.DrawIndicator = true;
			this.checkSelfDelivery.UseUnderline = true;
			this.checkSelfDelivery.InheritedDataSource = true;
			this.checkSelfDelivery.Mappings = "SelfDelivery";
			this.checkSelfDelivery.InheritedBoundaryDataSource = false;
			this.checkSelfDelivery.Editable = true;
			this.checkSelfDelivery.AutomaticTitle = false;
			this.checkSelfDelivery.InheritedBoundaryDataSource = false;
			this.checkSelfDelivery.InheritedDataSource = true;
			this.checkSelfDelivery.Mappings = "SelfDelivery";
			this.datatable1.Add (this.checkSelfDelivery);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.checkSelfDelivery]));
			w13.TopAttach = ((uint)(6));
			w13.BottomAttach = ((uint)(7));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(1));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumPaymentType = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumPaymentType.Name = "enumPaymentType";
			this.enumPaymentType.InheritedBoundaryDataSource = false;
			this.enumPaymentType.InheritedDataSource = true;
			this.enumPaymentType.Mappings = "PaymentType";
			this.enumPaymentType.InheritedBoundaryDataSource = false;
			this.enumPaymentType.InheritedDataSource = true;
			this.enumPaymentType.Mappings = "PaymentType";
			this.datatable1.Add (this.enumPaymentType);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumPaymentType]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumSignatureType = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumSignatureType.Name = "enumSignatureType";
			this.enumSignatureType.InheritedBoundaryDataSource = false;
			this.enumSignatureType.InheritedDataSource = true;
			this.enumSignatureType.Mappings = "SignatureType";
			this.enumSignatureType.InheritedBoundaryDataSource = false;
			this.enumSignatureType.InheritedDataSource = true;
			this.enumSignatureType.Mappings = "SignatureType";
			this.datatable1.Add (this.enumSignatureType);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumSignatureType]));
			w15.TopAttach = ((uint)(9));
			w15.BottomAttach = ((uint)(10));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.enumStatus = new global::Gtk.DataBindings.DataEnumComboBox ();
			this.enumStatus.Name = "enumStatus";
			this.enumStatus.InheritedBoundaryDataSource = false;
			this.enumStatus.InheritedDataSource = true;
			this.enumStatus.Mappings = "OrderStatus";
			this.enumStatus.InheritedBoundaryDataSource = false;
			this.enumStatus.InheritedDataSource = true;
			this.enumStatus.Mappings = "OrderStatus";
			this.datatable1.Add (this.enumStatus);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.enumStatus]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textComments = new global::Gtk.DataBindings.DataTextView ();
			this.textComments.CanFocus = true;
			this.textComments.Name = "textComments";
			this.textComments.InheritedDataSource = true;
			this.textComments.Mappings = "Comment";
			this.textComments.InheritedBoundaryDataSource = false;
			this.textComments.InheritedDataSource = true;
			this.textComments.Mappings = "Comment";
			this.textComments.InheritedBoundaryDataSource = false;
			this.GtkScrolledWindow.Add (this.textComments);
			this.datatable1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.GtkScrolledWindow]));
			w18.TopAttach = ((uint)(10));
			w18.BottomAttach = ((uint)(11));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.datatable1.Add (this.hseparator5);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.hseparator5]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.RightAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.datatable1.Add (this.hseparator6);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.hseparator6]));
			w20.TopAttach = ((uint)(8));
			w20.BottomAttach = ((uint)(9));
			w20.RightAttach = ((uint)(4));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Статус:");
			this.datatable1.Add (this.label1);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label1]));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.datatable1.Add (this.label10);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label10]));
			w22.TopAttach = ((uint)(10));
			w22.BottomAttach = ((uint)(11));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 160;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Клиент:");
			this.datatable1.Add (this.label2);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label2]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Точка доставки:");
			this.datatable1.Add (this.label3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label3]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Форма оплаты:");
			this.datatable1.Add (this.label4);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label4]));
			w25.TopAttach = ((uint)(4));
			w25.BottomAttach = ((uint)(5));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Подписание документов:");
			this.datatable1.Add (this.label9);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label9]));
			w26.TopAttach = ((uint)(9));
			w26.BottomAttach = ((uint)(10));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.labelDeliveryDate = new global::Gtk.Label ();
			this.labelDeliveryDate.WidthRequest = 160;
			this.labelDeliveryDate.Name = "labelDeliveryDate";
			this.labelDeliveryDate.Xalign = 1F;
			this.labelDeliveryDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата доставки:");
			this.datatable1.Add (this.labelDeliveryDate);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.labelDeliveryDate]));
			w27.TopAttach = ((uint)(7));
			w27.BottomAttach = ((uint)(8));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.labelDeliverySchedule = new global::Gtk.Label ();
			this.labelDeliverySchedule.Name = "labelDeliverySchedule";
			this.labelDeliverySchedule.Xalign = 1F;
			this.labelDeliverySchedule.LabelProp = global::Mono.Unix.Catalog.GetString ("Время доставки:");
			this.datatable1.Add (this.labelDeliverySchedule);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.labelDeliverySchedule]));
			w28.TopAttach = ((uint)(7));
			w28.BottomAttach = ((uint)(8));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.labelPreviousOrder = new global::Gtk.Label ();
			this.labelPreviousOrder.Name = "labelPreviousOrder";
			this.labelPreviousOrder.LabelProp = global::Mono.Unix.Catalog.GetString ("Предыдущий заказ.");
			this.labelPreviousOrder.UseMarkup = true;
			this.datatable1.Add (this.labelPreviousOrder);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.labelPreviousOrder]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.RightAttach = ((uint)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(2));
			// Container child datatable1.Gtk.Table+TableChild
			this.pickerDeliveryDate = new global::QSOrmProject.DataDatePicker ();
			this.pickerDeliveryDate.Events = ((global::Gdk.EventMask)(256));
			this.pickerDeliveryDate.Name = "pickerDeliveryDate";
			this.pickerDeliveryDate.Date = new global::System.DateTime (0);
			this.pickerDeliveryDate.IsEditable = true;
			this.pickerDeliveryDate.AutoSeparation = false;
			this.pickerDeliveryDate.InheritedDataSource = true;
			this.pickerDeliveryDate.Mappings = "DeliveryDate";
			this.pickerDeliveryDate.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.pickerDeliveryDate);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.pickerDeliveryDate]));
			w30.TopAttach = ((uint)(7));
			w30.BottomAttach = ((uint)(8));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceClient = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceClient.Events = ((global::Gdk.EventMask)(256));
			this.referenceClient.Name = "referenceClient";
			this.referenceClient.DisplayFields = new string[] {
				"Name"
			};
			this.referenceClient.DisplayFormatString = "{0}";
			this.referenceClient.InheritedDataSource = true;
			this.referenceClient.Mappings = "Client";
			this.referenceClient.InheritedBoundaryDataSource = false;
			this.referenceClient.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceClient);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceClient]));
			w31.TopAttach = ((uint)(2));
			w31.BottomAttach = ((uint)(3));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceDeliveryPoint = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceDeliveryPoint.Events = ((global::Gdk.EventMask)(256));
			this.referenceDeliveryPoint.Name = "referenceDeliveryPoint";
			this.referenceDeliveryPoint.DisplayFields = new string[] {
				"Name"
			};
			this.referenceDeliveryPoint.DisplayFormatString = "{0}";
			this.referenceDeliveryPoint.InheritedDataSource = true;
			this.referenceDeliveryPoint.Mappings = "DeliveryPoint";
			this.referenceDeliveryPoint.InheritedBoundaryDataSource = false;
			this.referenceDeliveryPoint.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceDeliveryPoint);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceDeliveryPoint]));
			w32.TopAttach = ((uint)(3));
			w32.BottomAttach = ((uint)(4));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.referenceDeliverySchedule = new global::Gtk.DataBindings.DataEntryReference ();
			this.referenceDeliverySchedule.Events = ((global::Gdk.EventMask)(256));
			this.referenceDeliverySchedule.Name = "referenceDeliverySchedule";
			this.referenceDeliverySchedule.DisplayFields = new string[] {
				"Name"
			};
			this.referenceDeliverySchedule.DisplayFormatString = "{0}";
			this.referenceDeliverySchedule.InheritedDataSource = true;
			this.referenceDeliverySchedule.Mappings = "DeliverySchedule";
			this.referenceDeliverySchedule.InheritedBoundaryDataSource = false;
			this.referenceDeliverySchedule.CursorPointsEveryType = false;
			this.datatable1.Add (this.referenceDeliverySchedule);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.referenceDeliverySchedule]));
			w33.TopAttach = ((uint)(7));
			w33.BottomAttach = ((uint)(8));
			w33.LeftAttach = ((uint)(3));
			w33.RightAttach = ((uint)(4));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.datatable1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.datatable1]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			this.notebook1.Add (this.vbox3);
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.vbox3, this.label13);
			this.label13.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeItems = new global::Gtk.DataBindings.DataTreeView ();
			this.treeItems.CanFocus = true;
			this.treeItems.Name = "treeItems";
			this.treeItems.CursorPointsEveryType = false;
			this.treeItems.InheritedDataSource = false;
			this.treeItems.InheritedBoundaryDataSource = false;
			this.treeItems.InheritedDataSource = false;
			this.treeItems.InheritedBoundaryDataSource = false;
			this.treeItems.ColumnMappings = "{Vodovoz.Domain.OrderItem} NomenclatureString[Номенклатура]; PriceString[Стоимость]; CountString[Количество];";
			this.GtkScrolledWindow1.Add (this.treeItems);
			this.hbox8.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.GtkScrolledWindow1]));
			w37.Position = 0;
			this.vbox4.Add (this.hbox8);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
			w38.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.datatable2 = new global::Gtk.DataBindings.DataTable (((uint)(1)), ((uint)(6)), false);
			this.datatable2.Name = "datatable2";
			this.datatable2.RowSpacing = ((uint)(6));
			this.datatable2.ColumnSpacing = ((uint)(6));
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			this.datatable2.InheritedDataSource = false;
			this.datatable2.InheritedBoundaryDataSource = false;
			// Container child datatable2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Сумма к получению:");
			this.datatable2.Add (this.label11);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label11]));
			w39.LeftAttach = ((uint)(4));
			w39.RightAttach = ((uint)(5));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Сумма:");
			this.datatable2.Add (this.label12);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label12]));
			w40.LeftAttach = ((uint)(2));
			w40.RightAttach = ((uint)(3));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Бутылей на возврат:");
			this.datatable2.Add (this.label7);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label7]));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.labelSum = new global::Gtk.Label ();
			this.labelSum.Name = "labelSum";
			this.labelSum.Xalign = 0F;
			this.labelSum.LabelProp = global::Mono.Unix.Catalog.GetString ("%$$$%");
			this.datatable2.Add (this.labelSum);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.labelSum]));
			w42.LeftAttach = ((uint)(3));
			w42.RightAttach = ((uint)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.spinBottlesReturn = new global::Gtk.DataBindings.DataSpinButton (0, 1000, 1);
			this.spinBottlesReturn.CanFocus = true;
			this.spinBottlesReturn.Name = "spinBottlesReturn";
			this.spinBottlesReturn.Adjustment.PageIncrement = 10;
			this.spinBottlesReturn.ClimbRate = 1;
			this.spinBottlesReturn.Numeric = true;
			this.spinBottlesReturn.InheritedDataSource = true;
			this.spinBottlesReturn.Mappings = "BottlesReturn";
			this.spinBottlesReturn.InheritedBoundaryDataSource = false;
			this.spinBottlesReturn.InheritedDataSource = true;
			this.spinBottlesReturn.Mappings = "BottlesReturn";
			this.spinBottlesReturn.InheritedBoundaryDataSource = false;
			this.datatable2.Add (this.spinBottlesReturn);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.spinBottlesReturn]));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.spinSumToReceive = new global::Gtk.DataBindings.DataSpinButton (0, 1000000, 1);
			this.spinSumToReceive.CanFocus = true;
			this.spinSumToReceive.Name = "spinSumToReceive";
			this.spinSumToReceive.Adjustment.PageIncrement = 10;
			this.spinSumToReceive.ClimbRate = 1;
			this.spinSumToReceive.Numeric = true;
			this.spinSumToReceive.InheritedDataSource = true;
			this.spinSumToReceive.Mappings = "SumToReceive";
			this.spinSumToReceive.InheritedBoundaryDataSource = false;
			this.spinSumToReceive.InheritedDataSource = true;
			this.spinSumToReceive.Mappings = "SumToReceive";
			this.spinSumToReceive.InheritedBoundaryDataSource = false;
			this.datatable2.Add (this.spinSumToReceive);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.spinSumToReceive]));
			w44.LeftAttach = ((uint)(5));
			w44.RightAttach = ((uint)(6));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.datatable2);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.datatable2]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonAddForSale = new global::Gtk.Button ();
			this.buttonAddForSale.CanFocus = true;
			this.buttonAddForSale.Name = "buttonAddForSale";
			this.buttonAddForSale.UseUnderline = true;
			this.buttonAddForSale.Label = global::Mono.Unix.Catalog.GetString ("На продажу");
			global::Gtk.Image w46 = new global::Gtk.Image ();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddForSale.Image = w46;
			this.hbox7.Add (this.buttonAddForSale);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonAddForSale]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.enumAddRentButton = new global::QSOrmProject.EnumMenuButton ();
			this.enumAddRentButton.CanFocus = true;
			this.enumAddRentButton.Name = "enumAddRentButton";
			this.enumAddRentButton.UseUnderline = true;
			this.enumAddRentButton.UseMarkup = false;
			this.enumAddRentButton.ItemsEnumName = "Vodovoz.Domain.OrderAgreementType, Vodovoz";
			this.enumAddRentButton.Label = global::Mono.Unix.Catalog.GetString ("В аренду");
			global::Gtk.Image w48 = new global::Gtk.Image ();
			w48.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.enumAddRentButton.Image = w48;
			this.hbox7.Add (this.enumAddRentButton);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.enumAddRentButton]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox7.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator2]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.Label = global::Mono.Unix.Catalog.GetString ("Удалить");
			global::Gtk.Image w51 = new global::Gtk.Image ();
			w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.buttonDelete.Image = w51;
			this.hbox7.Add (this.buttonDelete);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonDelete]));
			w52.Position = 3;
			w52.Expand = false;
			w52.Fill = false;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			this.notebook1.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w54 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox4]));
			w54.Position = 1;
			// Notebook tab
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Товары");
			this.notebook1.SetTabLabel (this.vbox4, this.label14);
			this.label14.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeEquipment = new global::Gtk.DataBindings.DataTreeView ();
			this.treeEquipment.CanFocus = true;
			this.treeEquipment.Name = "treeEquipment";
			this.treeEquipment.CursorPointsEveryType = false;
			this.treeEquipment.InheritedDataSource = false;
			this.treeEquipment.InheritedBoundaryDataSource = false;
			this.treeEquipment.InheritedDataSource = false;
			this.treeEquipment.InheritedBoundaryDataSource = false;
			this.treeEquipment.ColumnMappings = "{Vodovoz.Domain.OrderEquipment} NameString[Наименование]; DirectionString[Направление]; ReasonString[Причина];";
			this.GtkScrolledWindow3.Add (this.treeEquipment);
			this.notebook1.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w56 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow3]));
			w56.Position = 2;
			// Notebook tab
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Оборудование");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow3, this.label15);
			this.label15.ShowAll ();
			// Notebook tab
			global::Gtk.Label w57 = new global::Gtk.Label ();
			w57.Visible = true;
			this.notebook1.Add (w57);
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Сервис");
			this.notebook1.SetTabLabel (w57, this.label17);
			this.label17.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeDocuments = new global::Gtk.DataBindings.DataTreeView ();
			this.treeDocuments.CanFocus = true;
			this.treeDocuments.Name = "treeDocuments";
			this.treeDocuments.CursorPointsEveryType = false;
			this.treeDocuments.InheritedDataSource = false;
			this.treeDocuments.InheritedBoundaryDataSource = false;
			this.treeDocuments.InheritedDataSource = false;
			this.treeDocuments.InheritedBoundaryDataSource = false;
			this.treeDocuments.ColumnMappings = "{Vodovoz.Domain.OrderDocument} Name[Документ];";
			this.GtkScrolledWindow2.Add (this.treeDocuments);
			this.hbox9.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.GtkScrolledWindow2]));
			w59.Position = 0;
			this.vbox5.Add (this.hbox9);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox9]));
			w60.Position = 0;
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w61 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w61.Position = 4;
			// Notebook tab
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Документы");
			this.notebook1.SetTabLabel (this.vbox5, this.label18);
			this.label18.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w62.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.toggleInformation.Toggled += new global::System.EventHandler (this.OnToggleInformationToggled);
			this.toggleGoods.Toggled += new global::System.EventHandler (this.OnToggleGoodsToggled);
			this.toggleEquipment.Toggled += new global::System.EventHandler (this.OnToggleEquipmentToggled);
			this.toggleService.Toggled += new global::System.EventHandler (this.OnToggleServiceToggled);
			this.toggleDocuments.Toggled += new global::System.EventHandler (this.OnToggleDocumentsToggled);
			this.referenceClient.Changed += new global::System.EventHandler (this.OnReferenceClientChanged);
			this.buttonAddForSale.Clicked += new global::System.EventHandler (this.OnButtonAddForSaleClicked);
			this.enumAddRentButton.EnumItemClicked += new global::System.EventHandler<QSOrmProject.EnumItemClickedEventArgs> (this.OnEnumAddRentButtonEnumItemClicked);
			this.buttonDelete.Clicked += new global::System.EventHandler (this.OnButtonDeleteClicked);
		}
	}
}
